

// Statystyki kolumn
// payment_sequential - raty, które pojawiają się po kolei w danym zamówieniu (1, 2, 3...)
// payment_type - dla jednego zamówienia może wystąpic dany rodzaj platnosci i dodatkowo voucher
EVALUATE
UNION (
    ROW (
        "Table", "olist_order_payments_dataset",
        "Column", "order_id",
        "Count", COUNT ( 'olist_order_payments_dataset'[order_id] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'olist_order_payments_dataset'[order_id] ),
        "Null Count",
            COUNTROWS ( 'olist_order_payments_dataset' )
                - COUNT ( 'olist_order_payments_dataset'[order_id] ),
        "Min", MIN ( 'olist_order_payments_dataset'[order_id] ),
        "Max", MAX ( 'olist_order_payments_dataset'[order_id] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "olist_order_payments_dataset",
        "Column", "payment_sequential",
        "Count", COUNT ( 'olist_order_payments_dataset'[payment_sequential] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'olist_order_payments_dataset'[payment_sequential] ),
        "Null Count",
            COUNTROWS ( 'olist_order_payments_dataset' )
                - COUNT ( 'olist_order_payments_dataset'[payment_sequential] ),
        "Min", MIN ( 'olist_order_payments_dataset'[payment_sequential] ),
        "Max", MAX ( 'olist_order_payments_dataset'[payment_sequential] ),
        "Median", MEDIAN ( 'olist_order_payments_dataset'[payment_sequential] ),
        "Mean", AVERAGE ( 'olist_order_payments_dataset'[payment_sequential] ),
        "Standard Deviation", STDEV.P ( 'olist_order_payments_dataset'[payment_sequential] ),
        "Zeros",
            COALESCE (
                COUNTROWS (
                    FILTER (
                        'olist_order_payments_dataset',
                        'olist_order_payments_dataset'[payment_sequential] = 0
                    )
                ),
                0
            ),
        "Evens",
            COALESCE (
                COUNTROWS (
                    FILTER (
                        'olist_order_payments_dataset',
                        MOD ( 'olist_order_payments_dataset'[payment_sequential], 2 ) = 0
                    )
                ),
                0
            ),
        "Odds",
            COALESCE (
                COUNTROWS (
                    FILTER (
                        'olist_order_payments_dataset',
                        MOD ( 'olist_order_payments_dataset'[payment_sequential], 2 ) <> 0
                    )
                ),
                0
            ),
        "P25", PERCENTILE.INC ( 'olist_order_payments_dataset'[payment_sequential], 0.25 ),
        "P75", PERCENTILE.INC ( 'olist_order_payments_dataset'[payment_sequential], 0.75 ),
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "olist_order_payments_dataset",
        "Column", "payment_type",
        "Count", COUNT ( 'olist_order_payments_dataset'[payment_type] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'olist_order_payments_dataset'[payment_type] ),
        "Null Count",
            COUNTROWS ( 'olist_order_payments_dataset' )
                - COUNT ( 'olist_order_payments_dataset'[payment_type] ),
        "Min", MIN ( 'olist_order_payments_dataset'[payment_type] ),
        "Max", MAX ( 'olist_order_payments_dataset'[payment_type] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "olist_order_payments_dataset",
        "Column", "payment_installments",
        "Count", COUNT ( 'olist_order_payments_dataset'[payment_installments] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'olist_order_payments_dataset'[payment_installments] ),
        "Null Count",
            COUNTROWS ( 'olist_order_payments_dataset' )
                - COUNT ( 'olist_order_payments_dataset'[payment_installments] ),
        "Min", MIN ( 'olist_order_payments_dataset'[payment_installments] ),
        "Max", MAX ( 'olist_order_payments_dataset'[payment_installments] ),
        "Median", MEDIAN ( 'olist_order_payments_dataset'[payment_installments] ),
        "Mean", AVERAGE ( 'olist_order_payments_dataset'[payment_installments] ),
        "Standard Deviation", STDEV.P ( 'olist_order_payments_dataset'[payment_installments] ),
        "Zeros",
            COALESCE (
                COUNTROWS (
                    FILTER (
                        'olist_order_payments_dataset',
                        'olist_order_payments_dataset'[payment_installments] = 0
                    )
                ),
                0
            ),
        "Evens",
            COALESCE (
                COUNTROWS (
                    FILTER (
                        'olist_order_payments_dataset',
                        MOD ( 'olist_order_payments_dataset'[payment_installments], 2 ) = 0
                    )
                ),
                0
            ),
        "Odds",
            COALESCE (
                COUNTROWS (
                    FILTER (
                        'olist_order_payments_dataset',
                        MOD ( 'olist_order_payments_dataset'[payment_installments], 2 ) <> 0
                    )
                ),
                0
            ),
        "P25", PERCENTILE.INC ( 'olist_order_payments_dataset'[payment_installments], 0.25 ),
        "P75", PERCENTILE.INC ( 'olist_order_payments_dataset'[payment_installments], 0.75 ),
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "olist_order_payments_dataset",
        "Column", "payment_value",
        "Count", COUNT ( 'olist_order_payments_dataset'[payment_value] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'olist_order_payments_dataset'[payment_value] ),
        "Null Count",
            COUNTROWS ( 'olist_order_payments_dataset' )
                - COUNT ( 'olist_order_payments_dataset'[payment_value] ),
        "Min", MIN ( 'olist_order_payments_dataset'[payment_value] ),
        "Max", MAX ( 'olist_order_payments_dataset'[payment_value] ),
        "Median", MEDIAN ( 'olist_order_payments_dataset'[payment_value] ),
        "Mean", AVERAGE ( 'olist_order_payments_dataset'[payment_value] ),
        "Standard Deviation", STDEV.P ( 'olist_order_payments_dataset'[payment_value] ),
        "Zeros",
            COALESCE (
                COUNTROWS (
                    FILTER (
                        'olist_order_payments_dataset',
                        'olist_order_payments_dataset'[payment_value] = 0
                    )
                ),
                0
            ),
        "Evens",
            COALESCE (
                COUNTROWS (
                    FILTER (
                        'olist_order_payments_dataset',
                        MOD ( 'olist_order_payments_dataset'[payment_value], 2 ) = 0
                    )
                ),
                0
            ),
        "Odds",
            COALESCE (
                COUNTROWS (
                    FILTER (
                        'olist_order_payments_dataset',
                        MOD ( 'olist_order_payments_dataset'[payment_value], 2 ) <> 0
                    )
                ),
                0
            ),
        "P25", PERCENTILE.INC ( 'olist_order_payments_dataset'[payment_value], 0.25 ),
        "P75", PERCENTILE.INC ( 'olist_order_payments_dataset'[payment_value], 0.75 ),
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    )
)


// Lista typów płatności
EVALUATE
DISTINCT(olist_order_payments_dataset[payment_type])

