

// Statystyki kolumn
EVALUATE
UNION (
    ROW (
        "Table", "product_category_name_translation",
        "Column", "product_category_name",
        "Count", COUNT ( 'product_category_name_translation'[product_category_name] ),
        "Distinct Values",
            DISTINCTCOUNTNOBLANK ( 'product_category_name_translation'[product_category_name] ),
        "Null Count",
            COUNTROWS ( 'product_category_name_translation' )
                - COUNT ( 'product_category_name_translation'[product_category_name] ),
        "Min", MIN ( 'product_category_name_translation'[product_category_name] ),
        "Max", MAX ( 'product_category_name_translation'[product_category_name] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "product_category_name_translation",
        "Column", "product_category_name_english",
        "Count", COUNT ( 'product_category_name_translation'[product_category_name_english] ),
        "Distinct Values",
            DISTINCTCOUNTNOBLANK ( 'product_category_name_translation'[product_category_name_english] ),
        "Null Count",
            COUNTROWS ( 'product_category_name_translation' )
                - COUNT ( 'product_category_name_translation'[product_category_name_english] ),
        "Min", MIN ( 'product_category_name_translation'[product_category_name_english] ),
        "Max", MAX ( 'product_category_name_translation'[product_category_name_english] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    )
)

