'Visual Measure'[% of Single Orders - Sparkline - Card - Sales] = 
// Static line color - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)
VAR LineColour = "%23344C69"
VAR PointColour = "%23F9F9F9"
VAR Defs = "<defs>
    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>
        <stop stop-color='#4D6A8D' offset='0' />
        <stop stop-color='#4D6A8D' offset='0.3' />
        <stop stop-color='#F9F9F9' offset='1' />
    </linearGradient>
</defs>" // "Date" field used in this example along the X axis
VAR XMinDate =
    MIN ( 'Calendar'[Start of Month] )
VAR XMaxDate =
    MAX ( 'Calendar'[Start of Month] ) // Obtain overall min and overall max measure values when evaluated for each date
VAR YMinValue =
    MINX (
        VALUES ( 'Calendar'[Start of Month] ),
        CALCULATE ( [% of Single Orders] )
    )
VAR YMaxValue =
    MAXX (
        VALUES ( 'Calendar'[Start of Month] ),
        CALCULATE ( [% of Single Orders] )
    ) // Build table of X & Y coordinates and fit to 50 x 150 viewbox
VAR SparklineTable =
    ADDCOLUMNS (
        SUMMARIZE ( 'Calendar', 'Calendar'[Start of Month] ),
        "X",
            INT (
                150
                    * DIVIDE ( 'Calendar'[Start of Month] - XMinDate, XMaxDate - XMinDate )
            ),
        "Y",
            INT ( 50 * DIVIDE ( [% of Single Orders] - YMinValue, YMaxValue - YMinValue ) )
    ) // Concatenate X & Y coordinates to build the sparkline
VAR Lines =
    CONCATENATEX (
        SparklineTable,
        [X] & "," & 50 - [Y],
        " ",
        'Calendar'[Start of Month]
    ) // Last data points on the line
VAR LastSparkYValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [Y] )
VAR LastSparkXValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [X] ) // Add to SVG, and verify Data Category is set to Image URL for this measure
VAR SVGImageURL = "data:image/svg+xml;utf8," & --- gradient---
"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>" & Defs & "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' 
      stroke-width='0' points=' 0 50 " & Lines & " 150 150 Z '/>" & --- Lines---
"<polyline 
        fill='transparent' stroke='" & LineColour & "' 
        stroke-linecap='round' stroke-linejoin='round' 
        stroke-width='2' points=' " & Lines & " '/>" & --- Last Point---
"<circle cx='" & LastSparkXValue & "' cy='" & 50 - LastSparkYValue & "' r='4' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" & "</svg>"
RETURN
    SVGImageURL

'Visual Measure'[% of Single Orders - Subtitle - Card - Sales] = 
VAR __Arrow =
    SWITCH (
        TRUE (),
        [LM MOM % % of Single Orders] > 0, UNICHAR ( 11165 ),
        [LM MOM % % of Single Orders] < 0, UNICHAR ( 11167 )
    )
VAR __Negative =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % % of Single Orders], "0.00%" ) & " MoM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Positive =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % % of Single Orders], "0.00%" ) & " MoM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Result =
    SWITCH (
        TRUE (),
        ISBLANK ( [LM MOM % % of Single Orders] ), "-",
        [LM MOM % % of Single Orders] = 0, "No MoM Change",
        [LM MOM % % of Single Orders] < 0, __Negative,
        [LM MOM % % of Single Orders] > 0, __Positive
    )
RETURN
    __Result

'Visual Measure'[AOV Rank - Payment - Tooltip - Customer] = 
VAR __CurrentPaymentTypeAOV = [Average Order Value (AOV) (Payments)]
VAR __AllPaymentTypesAOV =
    ADDCOLUMNS (
        ALL ( 'Payment Type'[Payment Type] ),
        "AOV", [Average Order Value (AOV) (Payments)]
    )
VAR __AOVRank =
    RANKX (
        __AllPaymentTypesAOV,
        [Average Order Value (AOV) (Payments)],
        __CurrentPaymentTypeAOV,
        DESC,
        DENSE
    )
VAR __Result = "Rank " & __AOVRank
RETURN
    __Result

'Visual Measure'[Approval Time Icon] = 
"data:image/svg+xml;utf8," & "<svg width='46' height='46' viewBox='0 0 46 46' fill='none' xmlns='http://www.w3.org/2000/svg'>
<g clip-path='url(#clip0_3020_89)'>
<path d='M40.4578 16.4628H28.0458V16.8107C28.0458 19.5929 25.7823 21.8565 23 21.8565C20.2178 21.8565 17.9542 19.5931 17.9542 16.8107V16.4628H5.54219C2.48617 16.4628 0 18.9492 0 22.0051V23.8339C0 26.2529 1.55791 28.3151 3.72316 29.0696L4.92051 40.8043C5.26835 43.5698 7.63262 45.6552 10.4197 45.6552H35.5806C38.3677 45.6552 40.7319 43.5698 41.0798 40.8043L42.2771 29.0696C44.4421 28.3151 46 26.2529 46 23.8339V22.0051C46 18.9492 43.5138 16.4628 40.4578 16.4628ZM16.2987 37.778C16.2987 38.8354 15.4415 39.6924 14.3841 39.6924C13.3266 39.6924 12.4694 38.8354 12.4694 37.778V30.2151C12.4694 29.1578 13.3266 28.3005 14.3841 28.3005C15.4414 28.3005 16.2987 29.1578 16.2987 30.2151V37.778ZM24.9147 37.778C24.9147 38.8354 24.0573 39.6924 23 39.6924C21.9427 39.6924 21.0853 38.8354 21.0853 37.778V30.2151C21.0853 29.1578 21.9427 28.3005 23 28.3005C24.0573 28.3005 24.9147 29.1578 24.9147 30.2151V37.778ZM33.5306 37.778C33.5306 38.8354 32.6734 39.6924 31.6159 39.6924C30.5586 39.6924 29.7013 38.8354 29.7013 37.778V30.2151C29.7013 29.1578 30.5585 28.3005 31.6159 28.3005C32.6734 28.3005 33.5306 29.1578 33.5306 30.2151V37.778Z' fill='#344C69'/>
<path d='M23.0008 19.8271C24.6666 19.8271 26.0171 18.4766 26.0171 16.8107V3.36111C26.0171 1.69523 24.6666 0.344727 23.0008 0.344727C21.3349 0.344727 19.9844 1.69523 19.9844 3.36111V16.8107C19.9844 18.4766 21.3349 19.8271 23.0008 19.8271Z' fill='#344C69'/>
</g>
<defs>
<clipPath id='clip0_3020_89'>
<rect width='46' height='46' fill='white'/>
</clipPath>
</defs>
</svg>
"

'Visual Measure'[Average Order Cancellation Rate - Subtitle - Card - Sales] = 
VAR __Arrow =
    SWITCH (
        TRUE (),
        [LM MOM % Average Order Cancellation Rate] > 0, UNICHAR ( 11165 ),
        [LM MOM % Average Order Cancellation Rate] < 0, UNICHAR ( 11167 )
    )
VAR __Negative =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Average Order Cancellation Rate], "0.00%" ) & " MoM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Positive =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Average Order Cancellation Rate], "0.00%" ) & " MoM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Result =
    SWITCH (
        TRUE (),
        ISBLANK ( [LM MOM % Average Order Cancellation Rate] ), "-",
        [LM MOM % Average Order Cancellation Rate] = 0, "No MoM Change",
        [LM MOM % Average Order Cancellation Rate] < 0, __Negative,
        [LM MOM % Average Order Cancellation Rate] > 0, __Positive
    )
RETURN
    __Result

'Visual Measure'[Average Order Cancellation Rate - Title Color - Card - Sales] = 
SWITCH (
    TRUE (),
    [LM MOM % Average Order Cancellation Rate] > 0, [Negative Color],
    [LM MOM % Average Order Cancellation Rate] < 0, [Positive Color]
)

'Visual Measure'[Average Order Freight Value - Sparkline - Card - Product] = 
// Static line color - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)
VAR LineColour = "%23344C69"
VAR PointColour = "%23F9F9F9"
VAR Defs = "<defs>
    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>
        <stop stop-color='#4D6A8D' offset='0' />
        <stop stop-color='#4D6A8D' offset='0.3' />
        <stop stop-color='#F9F9F9' offset='1' />
    </linearGradient>
</defs>" // "Date" field used Total Categories along the X axis
VAR XMinDate =
    MIN ( 'Calendar'[Start of Month] )
VAR XMaxDate =
    MAX ( 'Calendar'[Start of Month] ) // Obtain overall min and overall max measure values when evaluated for each date
VAR YMinValue =
    MINX (
        VALUES ( 'Calendar'[Start of Month] ),
        CALCULATE ( [Average Order Freight Value] )
    )
VAR YMaxValue =
    MAXX (
        VALUES ( 'Calendar'[Start of Month] ),
        CALCULATE ( [Average Order Freight Value] )
    ) // Build table of X & Y coordinates and fit to 50 x 150 viewbox
VAR SparklineTable =
    ADDCOLUMNS (
        SUMMARIZE ( 'Calendar', 'Calendar'[Start of Month] ),
        "X",
            INT (
                150
                    * DIVIDE ( 'Calendar'[Start of Month] - XMinDate, XMaxDate - XMinDate )
            ),
        "Y",
            INT (
                50
                    * DIVIDE ( [Average Order Freight Value] - YMinValue, YMaxValue - YMinValue )
            )
    ) // Concatenate X & Y coordinates to build the sparkline
VAR Lines =
    CONCATENATEX (
        SparklineTable,
        [X] & "," & 50 - [Y],
        " ",
        'Calendar'[Start of Month]
    ) // Last data points on the line
VAR LastSparkYValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [Y] )
VAR LastSparkXValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [X] ) // Add to SVG, and verify Data Category is set to Image URL for this measure
VAR SVGImageURL = "data:image/svg+xml;utf8," & --- gradient---
"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>" & Defs & "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' 
      stroke-width='0' points=' 0 50 " & Lines & " 150 150 Z '/>" & --- Lines---
"<polyline 
        fill='transparent' stroke='" & LineColour & "' 
        stroke-linecap='round' stroke-linejoin='round' 
        stroke-width='2' points=' " & Lines & " '/>" & --- Last Point---
"<circle cx='" & LastSparkXValue & "' cy='" & 50 - LastSparkYValue & "' r='4' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" & "</svg>"
RETURN
    SVGImageURL

'Visual Measure'[Average Order Freight Value - Subtitle - Card - Sales] = 
VAR __Arrow =
    SWITCH (
        TRUE (),
        [LM MOM % Average Order Freight Value] > 0, UNICHAR ( 11165 ),
        [LM MOM % Average Order Freight Value] < 0, UNICHAR ( 11167 )
    )
VAR __Negative =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Average Order Freight Value], "0.00%" ) & " MoM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Positive =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Average Order Freight Value], "0.00%" ) & " MoM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Result =
    SWITCH (
        TRUE (),
        ISBLANK ( [LM MOM % Average Order Freight Value] ), "-",
        [LM MOM % Average Order Freight Value] = 0, "No MoM Change",
        [LM MOM % Average Order Freight Value] < 0, __Negative,
        [LM MOM % Average Order Freight Value] > 0, __Positive
    )
RETURN
    __Result

'Visual Measure'[Average Order Value - Sparkline - Card - Sales] = 
// Static line color - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)
VAR LineColour = "%23344C69"
VAR PointColour = "%23F9F9F9"
VAR Defs = "<defs>
    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>
        <stop stop-color='#4D6A8D' offset='0' />
        <stop stop-color='#4D6A8D' offset='0.3' />
        <stop stop-color='#F9F9F9' offset='1' />
    </linearGradient>
</defs>" // "Date" field used in this example along the X axis
VAR XMinDate =
    MIN ( 'Calendar'[Start of Month] )
VAR XMaxDate =
    MAX ( 'Calendar'[Start of Month] ) // Obtain overall min and overall max measure values when evaluated for each date
VAR YMinValue =
    MINX (
        VALUES ( 'Calendar'[Start of Month] ),
        CALCULATE ( [Average Order Value (AOV)] )
    )
VAR YMaxValue =
    MAXX (
        VALUES ( 'Calendar'[Start of Month] ),
        CALCULATE ( [Average Order Value (AOV)] )
    ) // Build table of X & Y coordinates and fit to 50 x 150 viewbox
VAR SparklineTable =
    ADDCOLUMNS (
        SUMMARIZE ( 'Calendar', 'Calendar'[Start of Month] ),
        "X",
            INT (
                150
                    * DIVIDE ( 'Calendar'[Start of Month] - XMinDate, XMaxDate - XMinDate )
            ),
        "Y",
            INT (
                50
                    * DIVIDE ( [Average Order Value (AOV)] - YMinValue, YMaxValue - YMinValue )
            )
    ) // Concatenate X & Y coordinates to build the sparkline
VAR Lines =
    CONCATENATEX (
        SparklineTable,
        [X] & "," & 50 - [Y],
        " ",
        'Calendar'[Start of Month]
    ) // Last data points on the line
VAR LastSparkYValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [Y] )
VAR LastSparkXValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [X] ) // Add to SVG, and verify Data Category is set to Image URL for this measure
VAR SVGImageURL = "data:image/svg+xml;utf8," & --- gradient---
"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>" & Defs & "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' 
      stroke-width='0' points=' 0 50 " & Lines & " 150 150 Z '/>" & --- Lines---
"<polyline 
        fill='transparent' stroke='" & LineColour & "' 
        stroke-linecap='round' stroke-linejoin='round' 
        stroke-width='2' points=' " & Lines & " '/>" & --- Last Point---
"<circle cx='" & LastSparkXValue & "' cy='" & 50 - LastSparkYValue & "' r='4' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" & "</svg>"
RETURN
    SVGImageURL

'Visual Measure'[Average Order Value (AOV) - Subtitle - Card - Sales] = 
VAR __Arrow =
    SWITCH (
        TRUE (),
        [LM MOM % Average Order Value (AOV)] > 0, UNICHAR ( 11165 ),
        [LM MOM % Average Order Value (AOV)] < 0, UNICHAR ( 11167 )
    )
VAR __Negative =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Average Order Value (AOV)], "0.00%" ) & " MoM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Positive =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Average Order Value (AOV)], "0.00%" ) & " MoM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Result =
    SWITCH (
        TRUE (),
        ISBLANK ( [LM MOM % Average Order Value (AOV)] ), "-",
        [LM MOM % Average Order Value (AOV)] = 0, "No MoM Change",
        [LM MOM % Average Order Value (AOV)] < 0, __Negative,
        [LM MOM % Average Order Value (AOV)] > 0, __Positive
    )
RETURN
    __Result

'Visual Measure'[Average Order Value (AOV) Inverted] = 
- [Average Order Value (AOV) (Payments)]

'Visual Measure'[Average Product Photos Quantity - Sparkline - Card - Product] = 
// Static line color - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)
VAR LineColour = "%23344C69"
VAR PointColour = "%23F9F9F9"
VAR Defs = "<defs>
    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>
        <stop stop-color='#4D6A8D' offset='0' />
        <stop stop-color='#4D6A8D' offset='0.3' />
        <stop stop-color='#F9F9F9' offset='1' />
    </linearGradient>
</defs>" // "Date" field used Total Categories along the X axis
VAR XMinDate =
    MIN ( 'Calendar'[Start of Month] )
VAR XMaxDate =
    MAX ( 'Calendar'[Start of Month] ) // Obtain overall min and overall max measure values when evaluated for each date
VAR YMinValue =
    MINX (
        VALUES ( 'Calendar'[Start of Month] ),
        CALCULATE ( [Average Product Photos Quantity] )
    )
VAR YMaxValue =
    MAXX (
        VALUES ( 'Calendar'[Start of Month] ),
        CALCULATE ( [Average Product Photos Quantity] )
    ) // Build table of X & Y coordinates and fit to 50 x 150 viewbox
VAR SparklineTable =
    ADDCOLUMNS (
        SUMMARIZE ( 'Calendar', 'Calendar'[Start of Month] ),
        "X",
            INT (
                150
                    * DIVIDE ( 'Calendar'[Start of Month] - XMinDate, XMaxDate - XMinDate )
            ),
        "Y",
            INT (
                50
                    * DIVIDE ( [Average Product Photos Quantity] - YMinValue, YMaxValue - YMinValue )
            )
    ) // Concatenate X & Y coordinates to build the sparkline
VAR Lines =
    CONCATENATEX (
        SparklineTable,
        [X] & "," & 50 - [Y],
        " ",
        'Calendar'[Start of Month]
    ) // Last data points on the line
VAR LastSparkYValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [Y] )
VAR LastSparkXValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [X] ) // Add to SVG, and verify Data Category is set to Image URL for this measure
VAR SVGImageURL = "data:image/svg+xml;utf8," & --- gradient---
"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>" & Defs & "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' 
      stroke-width='0' points=' 0 50 " & Lines & " 150 150 Z '/>" & --- Lines---
"<polyline 
        fill='transparent' stroke='" & LineColour & "' 
        stroke-linecap='round' stroke-linejoin='round' 
        stroke-width='2' points=' " & Lines & " '/>" & --- Last Point---
"<circle cx='" & LastSparkXValue & "' cy='" & 50 - LastSparkYValue & "' r='4' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" & "</svg>"
RETURN
    SVGImageURL

'Visual Measure'[Average Product Photos Quantity - Subtitle - Card - Product] = 
VAR __Arrow =
    SWITCH (
        TRUE (),
        [LM MOM % Average Product Photos Quantity] > 0, UNICHAR ( 11165 ),
        [LM MOM % Average Product Photos Quantity] < 0, UNICHAR ( 11167 )
    )
VAR __Negative =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Average Product Photos Quantity], "0.00%" ) & " MOM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Positive =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Average Product Photos Quantity], "0.00%" ) & " MOM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Result =
    SWITCH (
        TRUE (),
        ISBLANK ( [LM MOM % Average Product Photos Quantity] ), "-",
        [LM MOM % Average Product Photos Quantity] = 0, "No MoM Change",
        [LM MOM % Average Product Photos Quantity] < 0, __Negative,
        [LM MOM % Average Product Photos Quantity] > 0, __Positive
    )
RETURN
    __Result

'Visual Measure'[Average Product Photos Quantity - Title Color - Card - Product] = 
SWITCH (
    TRUE (),
    [LM MOM % Average Product Photos Quantity] > 0, [Positive Color],
    [LM MOM % Average Product Photos Quantity] < 0, [Negative Color]
)

'Visual Measure'[Average Product Volume - Sparkline - Card - Product] = 
// Static line color - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)
VAR LineColour = "%23344C69"
VAR PointColour = "%23F9F9F9"
VAR Defs = "<defs>
    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>
        <stop stop-color='#4D6A8D' offset='0' />
        <stop stop-color='#4D6A8D' offset='0.3' />
        <stop stop-color='#F9F9F9' offset='1' />
    </linearGradient>
</defs>" // "Date" field used Total Categories along the X axis
VAR XMinDate =
    MIN ( 'Calendar'[Start of Month] )
VAR XMaxDate =
    MAX ( 'Calendar'[Start of Month] ) // Obtain overall min and overall max measure values when evaluated for each date
VAR YMinValue =
    MINX (
        VALUES ( 'Calendar'[Start of Month] ),
        CALCULATE ( [Average Product Volume] )
    )
VAR YMaxValue =
    MAXX (
        VALUES ( 'Calendar'[Start of Month] ),
        CALCULATE ( [Average Product Volume] )
    ) // Build table of X & Y coordinates and fit to 50 x 150 viewbox
VAR SparklineTable =
    ADDCOLUMNS (
        SUMMARIZE ( 'Calendar', 'Calendar'[Start of Month] ),
        "X",
            INT (
                150
                    * DIVIDE ( 'Calendar'[Start of Month] - XMinDate, XMaxDate - XMinDate )
            ),
        "Y",
            INT (
                50
                    * DIVIDE ( [Average Product Volume] - YMinValue, YMaxValue - YMinValue )
            )
    ) // Concatenate X & Y coordinates to build the sparkline
VAR Lines =
    CONCATENATEX (
        SparklineTable,
        [X] & "," & 50 - [Y],
        " ",
        'Calendar'[Start of Month]
    ) // Last data points on the line
VAR LastSparkYValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [Y] )
VAR LastSparkXValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [X] ) // Add to SVG, and verify Data Category is set to Image URL for this measure
VAR SVGImageURL = "data:image/svg+xml;utf8," & --- gradient---
"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>" & Defs & "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' 
      stroke-width='0' points=' 0 50 " & Lines & " 150 150 Z '/>" & --- Lines---
"<polyline 
        fill='transparent' stroke='" & LineColour & "' 
        stroke-linecap='round' stroke-linejoin='round' 
        stroke-width='2' points=' " & Lines & " '/>" & --- Last Point---
"<circle cx='" & LastSparkXValue & "' cy='" & 50 - LastSparkYValue & "' r='4' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" & "</svg>"
RETURN
    SVGImageURL

'Visual Measure'[Average Product Volume - Subtitle - Card - Product] = 
VAR __Arrow =
    SWITCH (
        TRUE (),
        [LM MOM % Average Product Volume] > 0, UNICHAR ( 11165 ),
        [LM MOM % Average Product Volume] < 0, UNICHAR ( 11167 )
    )
VAR __Negative =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Average Product Volume], "0.00%" ) & " MOM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Positive =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Average Product Volume], "0.00%" ) & " MOM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Result =
    SWITCH (
        TRUE (),
        ISBLANK ( [LM MOM % Average Product Volume] ), "-",
        [LM MOM % Average Product Volume] = 0, "No MoM Change",
        [LM MOM % Average Product Volume] < 0, __Negative,
        [LM MOM % Average Product Volume] > 0, __Positive
    )
RETURN
    __Result

'Visual Measure'[Blank] = 
BLANK ()

'Visual Measure'[Blank2] = 
BLANK ()

'Visual Measure'[Blank3] = 
BLANK ()

'Visual Measure'[Cambridge Blue] = 
"#7FACAC"

'Visual Measure'[Carrier Delivery Time Icon] = 
"data:image/svg+xml;utf8," & "<svg width='46' height='35' viewBox='0 0 46 35' fill='none' xmlns='http://www.w3.org/2000/svg'>
<path d='M2.61625 0.525635C1.17156 0.525635 0 1.70079 0 3.14188V27.2056C0 28.6467 1.31531 29.9656 2.76 29.9656H6.52625C6.96469 32.5747 9.22875 34.5656 11.96 34.5656C14.6913 34.5656 16.9553 32.5747 17.3938 29.9656H25.9038C27.3448 29.9656 28.52 28.7905 28.52 27.3494V3.19938C28.52 1.72595 27.3592 0.525635 25.9325 0.525635H2.61625ZM30.36 6.96563V29.9656C30.802 32.5711 33.1488 34.5656 35.88 34.5656C38.6113 34.5656 40.8753 32.5711 41.3138 29.9656H43.24C44.6847 29.9656 46 28.6503 46 27.2056V18.3506C46 16.4999 44.6667 14.6095 44.505 14.3831L40.6813 9.26563C39.8044 8.20907 38.428 6.96563 36.8 6.96563H30.36ZM34.96 11.5656H40.1063L43.0388 15.4756C43.3514 15.9177 44.16 17.2725 44.16 18.3506V18.9256H34.96C34.04 18.9256 33.12 18.0056 33.12 17.0856V13.4056C33.12 12.3886 34.04 11.5656 34.96 11.5656ZM11.96 25.3656C13.9905 25.3656 15.64 27.0152 15.64 29.0456C15.64 31.0761 13.9905 32.7256 11.96 32.7256C9.92953 32.7256 8.28 31.0761 8.28 29.0456C8.28 27.0152 9.92953 25.3656 11.96 25.3656ZM35.88 25.3656C37.9105 25.3656 39.56 27.0152 39.56 29.0456C39.56 31.0761 37.9105 32.7256 35.88 32.7256C33.8495 32.7256 32.2 31.0761 32.2 29.0456C32.2 27.0152 33.8495 25.3656 35.88 25.3656Z' fill='#344C69'/>
</svg>"

'Visual Measure'[Category Name - Product - Tooltip - Product] = 
SWITCH (
    TRUE (),
    MAX ( 'Product Category Field'[Product Category Field] ) = "Product",
        CALCULATE (
            MAX ( 'Category'[Category Name] ),
            TREATAS ( VALUES ( 'Product'[Category Id] ), Category[Category Id] )
        ),
    MAX ( 'Product Category Field'[Product Category Field] ) = "Category", SELECTEDVALUE ( Category[Category Name] )
)

'Visual Measure'[Cohort Metric - Background Color - Matrix - Retention] = 
VAR __FormattingMode =
    SELECTEDVALUE ( 'Cohort Formatting Mode'[ID] )
VAR __Min =
    CALCULATE (
        MINX (
            CROSSJOIN (
                DISTINCT ( 'Calendar'[Month Year] ),
                DISTINCT ( 'Order'[Months Since First Transaction] )
            ),
            [Selected Cohort Metric]
        ),
        ALLSELECTED ()
    )
VAR __Max =
    CALCULATE (
        MAXX (
            CROSSJOIN (
                DISTINCT ( 'Calendar'[Month Year] ),
                DISTINCT ( 'Order'[Months Since First Transaction] )
            ),
            [Selected Cohort Metric]
        ),
        ALLSELECTED ()
    )
VAR __Min_2 =
    MIN ( __Min, 0 )
VAR __Span = __Max - __Min_2
VAR __Norm =
    DIVIDE ( [Selected Cohort Metric] - __Min_2, __Span )
VAR __Lightness =
    100
        - ROUND ( __Norm * 80, 0 )
VAR __Hue = 210
VAR __Saturation = 45
VAR __Color = "hsla(" & __Hue & "," & __Saturation & "%," & __Lightness & "%," & "0.9)"
VAR __Result =
    SWITCH (
        TRUE (),
        __FormattingMode = 1, __Color,
        __FormattingMode = 2, __Color,
        __FormattingMode = 3, [Transparent Color],
        __Color
    )
RETURN
    __Result

'Visual Measure'[Cohort Metric - Font Color - Matrix - Retention] = 
VAR __FormattingMode =
    SELECTEDVALUE ( 'Cohort Formatting Mode'[ID] )
VAR __Min =
    CALCULATE (
        MINX (
            CROSSJOIN (
                DISTINCT ( 'Calendar'[Month Year] ),
                DISTINCT ( 'Order'[Months Since First Transaction] )
            ),
            [Selected Cohort Metric]
        ),
        ALLSELECTED ()
    )
VAR __Max =
    CALCULATE (
        MAXX (
            CROSSJOIN (
                DISTINCT ( 'Calendar'[Month Year] ),
                DISTINCT ( 'Order'[Months Since First Transaction] )
            ),
            [Selected Cohort Metric]
        ),
        ALLSELECTED ()
    )
VAR __Min_2 =
    MIN ( __Min, 0 )
VAR __Span = __Max - __Min_2
VAR __Norm =
    DIVIDE ( [Selected Cohort Metric] - __Min_2, __Span )
VAR __Lightness =
    100
        - ROUND ( __Norm * 80, 0 )
VAR __FontColor =
    IF ( __Lightness < 56, "#FFFFFF", "#223144" )
VAR __Result =
    SWITCH (
        TRUE (),
        __FormattingMode = 1, __FontColor,
        __FormattingMode = 2, [Transparent Color],
        __FormattingMode = 3, [Standard Blue],
        [Standard Blue]
    )
RETURN
    __Result

'Visual Measure'[Cohort Metric - Title - Matrix - Retention] = 
VAR __SelectedMetric =
    SWITCH (
        TRUE (),
        MAX ( 'Cohort Metric'[Cohort Metric] ) = "Cohort Performance", "Cohort Performance",
        MAX ( 'Cohort Metric'[Cohort Metric] ) = "Retention Rate", "Retention Rate"
    )
VAR __SelectedFormattingMode =
    SELECTEDVALUE ( 'Cohort Formatting Mode'[ID] )
VAR __Result = "Monthly " & __SelectedMetric
RETURN
    __Result

'Visual Measure'[Cumulative Product Metric - Pareto Category - Product] = 
IF (
    ISINSCOPE ( Category[Category Name] ),
    CALCULATE (
        [Selected Product Metric],
        TOPN (
            [Product Metric Rank - Pareto Category - Product],
            ALLSELECTED ( Category[Category Name] ),
            [Selected Product Metric],
        )
    ),
    CALCULATE ( [Selected Product Metric], ALLSELECTED ( Category[Category Name] ) )
)

'Visual Measure'[Cumulative Product Metric % - Axis - Pareto Category - Product] = 
VAR __MaxValue =
    MAXX (
        VALUES ( Category[Category Name] ),
        [Cumulative Product Metric % - Pareto Category - Product]
    )
VAR __Result = __MaxValue * 1.15
RETURN
    __Result

'Visual Measure'[Cumulative Product Metric % - Pareto Category - Product] = 
DIVIDE (
    [Cumulative Product Metric - Pareto Category - Product],
    [Total Product Metric - Pareto Category - Product]
)

'Visual Measure'[Cumulative Sales Metric - Pareto Seller - Sales] = 
IF (
    ISINSCOPE ( Seller[Seller Id] ),
    CALCULATE (
        [Selected Sales Metric],
        TOPN (
            [Sales Metric Rank - Pareto Seller - Sales],
            ALLSELECTED ( Seller[Seller Id] ),
            [Selected Sales Metric],
        )
    ),
    CALCULATE ( [Selected Sales Metric], ALLSELECTED ( Seller[Seller Id] ) )
)

'Visual Measure'[Cumulative Sales Metric % - Axis - Pareto Seller - Sales] = 
VAR __MaxValue =
    MAXX (
        VALUES ( Seller[Seller Id] ),
        [Cumulative Sales Metric % - Pareto Seller - Sales]
    )
VAR __Result = __MaxValue * 1.15
RETURN
    __Result

'Visual Measure'[Cumulative Sales Metric % - Pareto Seller - Sales] = 
DIVIDE (
    [Cumulative Sales Metric - Pareto Seller - Sales],
    [Total Sales Metric - Pareto Seller - Sales]
)

'Visual Measure'[Current Parameter Date Granularity] = 
MAX ( 'Parameter Date'[Parameter Date] )

'Visual Measure'[Customer Delivery Time Icon] = 
"data:image/svg+xml;utf8," & "<svg width='46' height='46' viewBox='0 0 46 46' fill='none' xmlns='http://www.w3.org/2000/svg'>
<path d='M24.9154 30.6665H21.082V42.1665H24.9154V30.6665Z' fill='#344C69'/>
<path d='M30.668 5.75022V9.79438L23.0013 3.22021L7.66797 16.3685V42.1669H17.2513V26.8335H28.7513V42.1669H38.3346V16.3685L34.5013 13.091V5.75022H30.668Z' fill='#344C69'/>
</svg>
"

'Visual Measure'[Customer Lifetime Value - Subtitle - Card - Customer] = 
VAR __Arrow =
    SWITCH (
        TRUE (),
        [LM MOM % Customer Lifetime Value (CLV) (Payments)] > 0, UNICHAR ( 11165 ),
        [LM MOM % Customer Lifetime Value (CLV) (Payments)] < 0, UNICHAR ( 11167 )
    )
VAR __Negative =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Customer Lifetime Value (CLV) (Payments)], "0.00%" ) & " MoM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Positive =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Customer Lifetime Value (CLV) (Payments)], "0.00%" ) & " MoM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Result =
    SWITCH (
        TRUE (),
        ISBLANK ( [LM MOM % Customer Lifetime Value (CLV) (Payments)] ), "-",
        [LM MOM % Customer Lifetime Value (CLV) (Payments)] = 0, "No MoM Change",
        [LM MOM % Customer Lifetime Value (CLV) (Payments)] < 0, __Negative,
        [LM MOM % Customer Lifetime Value (CLV) (Payments)] > 0, __Positive
    )
RETURN
    __Result

'Visual Measure'[Customer Lifetime Value (CLV) - Sparkline - Card - Customer] = 
// Static line color - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)
VAR LineColour = "%23344C69"
VAR PointColour = "%23F9F9F9"
VAR Defs = "<defs>
    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>
        <stop stop-color='#4D6A8D' offset='0' />
        <stop stop-color='#4D6A8D' offset='0.3' />
        <stop stop-color='#F9F9F9' offset='1' />
    </linearGradient>
</defs>" // "Date" field used in this example along the X axis
VAR XMinDate =
    MIN ( 'Calendar'[Start of Month] )
VAR XMaxDate =
    MAX ( 'Calendar'[Start of Month] ) // Obtain overall min and overall max measure values when evaluated for each date
VAR YMinValue =
    MINX (
        VALUES ( 'Calendar'[Start of Month] ),
        CALCULATE ( [Customer Lifetime Value (CLV) (Payments)] )
    )
VAR YMaxValue =
    MAXX (
        VALUES ( 'Calendar'[Start of Month] ),
        CALCULATE ( [Customer Lifetime Value (CLV) (Payments)] )
    ) // Build table of X & Y coordinates and fit to 50 x 150 viewbox
VAR SparklineTable =
    ADDCOLUMNS (
        SUMMARIZE ( 'Calendar', 'Calendar'[Start of Month] ),
        "X",
            INT (
                150
                    * DIVIDE ( 'Calendar'[Start of Month] - XMinDate, XMaxDate - XMinDate )
            ),
        "Y",
            INT (
                50
                    * DIVIDE (
                        [Customer Lifetime Value (CLV) (Payments)] - YMinValue,
                        YMaxValue - YMinValue
                    )
            )
    ) // Concatenate X & Y coordinates to build the sparkline
VAR Lines =
    CONCATENATEX (
        SparklineTable,
        [X] & "," & 50 - [Y],
        " ",
        'Calendar'[Start of Month]
    ) // Last data points on the line
VAR LastSparkYValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [Y] )
VAR LastSparkXValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [X] ) // Add to SVG, and verify Data Category is set to Image URL for this measure
VAR SVGImageURL = "data:image/svg+xml;utf8," & --- gradient---
"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>" & Defs & "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' 
      stroke-width='0' points=' 0 50 " & Lines & " 150 150 Z '/>" & --- Lines---
"<polyline 
        fill='transparent' stroke='" & LineColour & "' 
        stroke-linecap='round' stroke-linejoin='round' 
        stroke-width='2' points=' " & Lines & " '/>" & --- Last Point---
"<circle cx='" & LastSparkXValue & "' cy='" & 50 - LastSparkYValue & "' r='4' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" & "</svg>"
RETURN
    SVGImageURL

'Visual Measure'[Customer Lifetime Value (CLV) - Title Color - Card - Customer] = 
SWITCH (
    TRUE (),
    [LM MOM % Customer Lifetime Value (CLV) (Payments)] > 0, [Positive Color],
    [LM MOM % Customer Lifetime Value (CLV) (Payments)] < 0, [Negative Color]
)

'Visual Measure'[Customers - Axis - Line Chart - Retention] = 
VAR __MaxValue =
    MAXX ( VALUES ( 'Calendar'[Start of Month] ), [Active Customers] )
VAR __Result = __MaxValue * 1.15
RETURN
    __Result

'Visual Measure'[Cutoff Cumulative Product Metric - Pareto Category - Product] = 
VAR __ClosestCategory = [Cutoff Product Metric Category - Pareto Category - Product]
VAR __Result =
    IF (
        SELECTEDVALUE ( Category[Category Name] ) = __ClosestCategory,
        [Cumulative Product Metric - Pareto Category - Product],
        BLANK ()
    )
RETURN
    __Result

'Visual Measure'[Cutoff Cumulative Sales Metric - Pareto Seller - Sales] = 
VAR __ClosestSeller = [Cutoff Sales Metric Seller - Pareto Seller - Sales]
VAR __Result =
    IF (
        SELECTEDVALUE ( Seller[Seller Id] ) = __ClosestSeller,
        [Cumulative Sales Metric - Pareto Seller - Sales],
        BLANK ()
    )
RETURN
    __Result

'Visual Measure'[Cutoff Product Metric % - Pareto Category - Product] = 
VAR __ClosestCategory = [Cutoff Product Metric Category - Pareto Category - Product]
VAR __Result =
    IF (
        SELECTEDVALUE ( Category[Category Name] ) = __ClosestCategory,
        [Cumulative Product Metric % - Pareto Category - Product],
        BLANK ()
    )
RETURN
    __Result

'Visual Measure'[Cutoff Product Metric Category - Pareto Category - Product] = 
VAR __TargetPercentage = [Product Metric Pareto Value]
VAR __ClosestCustomer =
    TOPN (
        1,
        ADDCOLUMNS (
            SUMMARIZE ( ALLSELECTED ( 'Category' ), Category[Category Name] ),
            "CumulativeProductMetricPercent", [Cumulative Product Metric % - Pareto Category - Product],
            "Difference",
                ABS ( [Cumulative Product Metric % - Pareto Category - Product] - __TargetPercentage )
        ),
        [Difference], ASC
    )
VAR __Result =
    MAXX ( __ClosestCustomer, Category[Category Name] )
RETURN
    __Result

'Visual Measure'[Cutoff Product Metric Rank - Pareto Category - Product] = 
VAR __ClosestCategory = [Cutoff Product Metric Category - Pareto Category - Product]
VAR __Result =
    IF (
        SELECTEDVALUE ( Category[Category Name] ) = __ClosestCategory,
        [Product Metric Rank - Pareto Category - Product],
        BLANK ()
    )
RETURN
    __Result

'Visual Measure'[Cutoff Sales Metric % - Pareto Seller - Sales] = 
VAR __ClosestSeller = [Cutoff Sales Metric Seller - Pareto Seller - Sales]
VAR __Result =
    IF (
        SELECTEDVALUE ( Seller[Seller Id] ) = __ClosestSeller,
        [Cumulative Sales Metric % - Pareto Seller - Sales],
        BLANK ()
    )
RETURN
    __Result

'Visual Measure'[Cutoff Sales Metric Rank - Pareto Seller - Sales] = 
VAR __ClosestSeller = [Cutoff Sales Metric Seller - Pareto Seller - Sales]
VAR __Result =
    IF (
        SELECTEDVALUE ( Seller[Seller Id] ) = __ClosestSeller,
        [Sales Metric Rank - Pareto Seller - Sales],
        BLANK ()
    )
RETURN
    __Result

'Visual Measure'[Cutoff Sales Metric Seller - Pareto Seller - Sales] = 
VAR __TargetPercentage = [Sales Metric Pareto Value]
VAR __ClosestCustomer =
    TOPN (
        1,
        ADDCOLUMNS (
            SUMMARIZE ( ALLSELECTED ( 'Seller' ), Seller[Seller Id] ),
            "CumulativeSalesMetricPercent", [Cumulative Sales Metric % - Pareto Seller - Sales],
            "Difference", ABS ( [Cumulative Sales Metric % - Pareto Seller - Sales] - __TargetPercentage )
        ),
        [Difference], ASC
    )
VAR __Result =
    MAXX ( __ClosestCustomer, Seller[Seller Id] )
RETURN
    __Result

'Visual Measure'[Date Range - Granurality - Subtitle] = 
VAR __DateRange = [Selected Date Range]
VAR __Granularity =
    SWITCH (
        TRUE (),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Date", "Daily",
        MAX ( 'Parameter Date'[Parameter Date] ) = "Month", "Monthly",
        MAX ( 'Parameter Date'[Parameter Date] ) = "Quarter", "Quarterly",
        MAX ( 'Parameter Date'[Parameter Date] ) = "Year", "Yearly"
    )
VAR __Result = "Date Range: " & __DateRange & ", " & __Granularity & " Granularity"
RETURN
    __Result

'Visual Measure'[Date Range - Monthly Granurality - Subtitle] = 
VAR __DateRange = [Selected Date Range]
VAR __Result = "Date Range: " & __DateRange & ", " & " Monthly Granularity"
RETURN
    __Result

'Visual Measure'[Delivery Metric - Axis - Line Chart - Delivery] = 
VAR __MaxValue =
    SWITCH (
        TRUE (),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Date", MAXX ( VALUES ( 'Calendar'[Date] ), [Selected Delivery Metric] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Month", MAXX ( VALUES ( 'Calendar'[Start of Month] ), [Selected Delivery Metric] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Quarter", MAXX ( VALUES ( 'Calendar'[Start of Quarter] ), [Selected Delivery Metric] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Year", MAXX ( VALUES ( 'Calendar'[Start of Year] ), [Selected Delivery Metric] )
    )
VAR __Result = __MaxValue * 1.15
RETURN
    __Result

'Visual Measure'[Delivery Metric - Label Color - Line Chart - Delivery] = 
VAR __CurrentDateParameterValue =
    SWITCH (
        TRUE (),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Date", SELECTEDVALUE ( 'Calendar'[Date] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Month", SELECTEDVALUE ( 'Calendar'[Start of Month] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Quarter", SELECTEDVALUE ( 'Calendar'[Start of Quarter] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Year", SELECTEDVALUE ( 'Calendar'[Start of Year] )
    )
VAR __MaxValue =
    SWITCH (
        TRUE (),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Date", MAXX ( ALLSELECTED ( 'Calendar'[Date] ), [Selected Delivery Metric] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Month", MAXX ( ALLSELECTED ( 'Calendar'[Start of Month] ), [Selected Delivery Metric] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Quarter",
            MAXX (
                ALLSELECTED ( 'Calendar'[Start of Quarter] ),
                [Selected Delivery Metric]
            ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Year", MAXX ( ALLSELECTED ( 'Calendar'[Start of Year] ), [Selected Delivery Metric] )
    )
VAR __MinValue =
    SWITCH (
        TRUE (),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Date", MINX ( ALLSELECTED ( 'Calendar'[Date] ), [Selected Delivery Metric] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Month", MINX ( ALLSELECTED ( 'Calendar'[Start of Month] ), [Selected Delivery Metric] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Quarter",
            MINX (
                ALLSELECTED ( 'Calendar'[Start of Quarter] ),
                [Selected Delivery Metric]
            ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Year", MINX ( ALLSELECTED ( 'Calendar'[Start of Year] ), [Selected Delivery Metric] )
    )
VAR __Result =
    IF (
        [Selected Delivery Metric] = __MaxValue
            || [Selected Delivery Metric] = __MinValue
            || __CurrentDateParameterValue = [Start Parameter Date Value]
            || __CurrentDateParameterValue = [End Parameter Date Value],
        [Focus Blue],
        [Transparent Color]
    )
RETURN
    __Result

'Visual Measure'[Delivery Metric - Title - Line Chart - Delivery] = 
VAR __SelectedMetric =
    SWITCH (
        TRUE (),
        MAX ( 'Delivery Metric'[Delivery Metric] ) = "Total", "Total Delivery Time",
        MAX ( 'Delivery Metric'[Delivery Metric] ) = "Approval", "Approval Time",
        MAX ( 'Delivery Metric'[Delivery Metric] ) = "Carrier", "Carrier Delivery Time",
        MAX ( 'Delivery Metric'[Delivery Metric] ) = "Customer", "Customer Delivery Time"
    )
VAR __Result = __SelectedMetric & " by " & [Current Parameter Date Granularity]
RETURN
    __Result

'Visual Measure'[Delivery Time - Axis - Area Chart - Delivery] = 
VAR __MaxValue =
    SWITCH (
        TRUE (),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Date", MAXX ( VALUES ( 'Calendar'[Date] ), [Average Total Delivery Time (h)] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Month",
            MAXX (
                VALUES ( 'Calendar'[Start of Month] ),
                [Average Total Delivery Time (h)]
            ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Quarter",
            MAXX (
                VALUES ( 'Calendar'[Start of Quarter] ),
                [Average Total Delivery Time (h)]
            ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Year", MAXX ( VALUES ( 'Calendar'[Start of Year] ), [Average Total Delivery Time (h)] )
    )
VAR __Result = __MaxValue * 1.15
RETURN
    __Result

'Visual Measure'[Delivery Time - Label Color - Area Chart - Delivery] = 
VAR __CurrentDateParameterValue =
    SWITCH (
        TRUE (),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Date", SELECTEDVALUE ( 'Calendar'[Date] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Month", SELECTEDVALUE ( 'Calendar'[Start of Month] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Quarter", SELECTEDVALUE ( 'Calendar'[Start of Quarter] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Year", SELECTEDVALUE ( 'Calendar'[Start of Year] )
    )
VAR __MaxValue =
    SWITCH (
        TRUE (),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Date", MAXX ( ALLSELECTED ( 'Calendar'[Date] ), [Average Total Delivery Time (h)] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Month",
            MAXX (
                ALLSELECTED ( 'Calendar'[Start of Month] ),
                [Average Total Delivery Time (h)]
            ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Quarter",
            MAXX (
                ALLSELECTED ( 'Calendar'[Start of Quarter] ),
                [Average Total Delivery Time (h)]
            ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Year",
            MAXX (
                ALLSELECTED ( 'Calendar'[Start of Year] ),
                [Average Total Delivery Time (h)]
            )
    )
VAR __MinValue =
    SWITCH (
        TRUE (),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Date", MINX ( ALLSELECTED ( 'Calendar'[Date] ), [Average Total Delivery Time (h)] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Month",
            MINX (
                ALLSELECTED ( 'Calendar'[Start of Month] ),
                [Average Total Delivery Time (h)]
            ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Quarter",
            MINX (
                ALLSELECTED ( 'Calendar'[Start of Quarter] ),
                [Average Total Delivery Time (h)]
            ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Year",
            MINX (
                ALLSELECTED ( 'Calendar'[Start of Year] ),
                [Average Total Delivery Time (h)]
            )
    )
VAR __Result =
    IF (
        [Average Total Delivery Time (h)] = __MaxValue
            || [Average Total Delivery Time (h)] = __MinValue
            || __CurrentDateParameterValue = [Start Parameter Date Value]
            || __CurrentDateParameterValue = [End Parameter Date Value],
        [Focus Blue],
        [Transparent Color]
    )
RETURN
    __Result

'Visual Measure'[Delivery Time - Marker Color - Waffle Delivery - Delivery] = 
VAR __ApprovalTime = [% of Approval Time] * 100
VAR __CarrierDeliveryTime = [% of Carrier Delivery Time] * 100
VAR __CustomerDeliveryTime = [% of Customer Delivery Time] * 100
VAR __Result =
    SWITCH (
        TRUE (),
        MAX ( Waffle[Value] ) > 0
            && MAX ( Waffle[Value] ) <= __CustomerDeliveryTime, [Standard Blue],
        MAX ( Waffle[Value] ) > __CustomerDeliveryTime
            && MAX ( Waffle[Value] ) <= __CustomerDeliveryTime + __CarrierDeliveryTime, [Cambridge Blue],
        MAX ( Waffle[Value] ) > __CustomerDeliveryTime + __CarrierDeliveryTime
            && MAX ( Waffle[Value] ) <= __CustomerDeliveryTime + __CarrierDeliveryTime + __ApprovalTime, [Light Grey]
    )
RETURN
    __Result

'Visual Measure'[Delivery Time - Title - Area Chart - Delivery] = 
"Delivery Time Breakdown by " & [Current Parameter Date Granularity]

'Visual Measure'[Delivery Time - Title - Box Plot - Delivery] = 
VAR __SelectedMetric =
    SWITCH (
        TRUE (),
        MAX ( 'Delivery Metric'[Delivery Metric] ) = "Total", "Total Delivery Time",
        MAX ( 'Delivery Metric'[Delivery Metric] ) = "Approval", "Approval Time",
        MAX ( 'Delivery Metric'[Delivery Metric] ) = "Carrier", "Carrier Deliver Time",
        MAX ( 'Delivery Metric'[Delivery Metric] ) = "Customer", "Customer Deliver Time"
    )
VAR __Result = __SelectedMetric & " Distribution by Quarter"
RETURN
    __Result

'Visual Measure'[Delivery Time Date Title - Date - Tooltip - Delivery] = 
SWITCH (
    TRUE (),
    MAX ( 'Parameter Date'[Parameter Date] ) = "Date", FORMAT ( SELECTEDVALUE ( 'Calendar'[Date] ), "DD MMM YYYY" ),
    MAX ( 'Parameter Date'[Parameter Date] ) = "Month", SELECTEDVALUE ( 'Calendar'[Month Year] ),
    MAX ( 'Parameter Date'[Parameter Date] ) = "Quarter", SELECTEDVALUE ( 'Calendar'[Quarter Year] ),
    MAX ( 'Parameter Date'[Parameter Date] ) = "Year", SELECTEDVALUE ( 'Calendar'[Year] )
)

'Visual Measure'[Delivery Time State - Axis - Bar Chart - Delivery] = 
VAR __MaxValue =
    MAXX ( ALLSELECTED ( State[State] ), [Average Total Delivery Time (h)] )
VAR __Result = __MaxValue * 1.4
RETURN
    __Result

'Visual Measure'[Delivery Time State - Bar Color - Bar State - Delivery] = 
VAR __SelectedStatesCount =
    CALCULATE ( DISTINCTCOUNT ( State[State] ), ALLSELECTED ( State[State] ) )
VAR __NumberOfTop =
    IF (
        __SelectedStatesCount >= 6,
        3,
        DIVIDE ( __SelectedStatesCount, 2 ) + MOD ( __SelectedStatesCount, 2 )
    )
VAR __StateRankDesc =
    IF (
        ISINSCOPE ( State[State] ),
        RANKX (
            ALLSELECTED ( State[State] ),
            [Average Total Delivery Time (h)],
            ,
            DESC,
            DENSE
        )
    )
VAR __StateRankAsc =
    IF (
        ISINSCOPE ( State[State] ),
        RANKX (
            ALLSELECTED ( State[State] ),
            [Average Total Delivery Time (h)],
            ,
            ASC,
            DENSE
        )
    )
VAR __Result =
    IF (
        ISBLANK ( __SelectedStatesCount )
            || __SelectedStatesCount <= 1,
        [Focus Blue],
        SWITCH (
            TRUE (),
            ISBLANK ( __StateRankAsc ), [Light Grey],
            __StateRankAsc <= __NumberOfTop, [Positive Color],
            __StateRankDesc <= __NumberOfTop, [Negative Color],
            [Light Grey]
        )
    )
RETURN
    __Result

'Visual Measure'[Delivery Time State - Label Color - Bar State - Delivery] = 
VAR __StateRankDesc =
    IF (
        ISINSCOPE ( State[State] ),
        RANKX ( ALLSELECTED ( State[State] ), [Average Total Delivery Time (h)] )
    )
VAR __StateRankAsc =
    IF (
        ISINSCOPE ( State[State] ),
        RANKX ( ALLSELECTED ( State[State] ), [Average Total Delivery Time (h)],, ASC )
    )
VAR __Result =
    SWITCH (
        TRUE (),
        __StateRankDesc <= 3, [Focus Blue],
        __StateRankAsc <= 3, [Focus Blue],
        [Transparent Color]
    )
RETURN
    __Result

'Visual Measure'[End Actual Month Value] = 
CALCULATE (
    LASTDATE ( 'Calendar'[Start of Month] ),
    ALLSELECTED ( 'Calendar' )
)

'Visual Measure'[End Forecast Month Value] = 
EDATE ( [End Actual Month Value], 6 )

'Visual Measure'[End Parameter Date Value] = 
SWITCH (
    TRUE (),
    MAX ( 'Parameter Date'[Parameter Date] ) = "Date", CALCULATE ( LASTDATE ( 'Calendar'[Date] ), ALLSELECTED ( 'Calendar' ) ),
    MAX ( 'Parameter Date'[Parameter Date] ) = "Month",
        CALCULATE (
            LASTDATE ( 'Calendar'[Start of Month] ),
            ALLSELECTED ( 'Calendar' )
        ),
    MAX ( 'Parameter Date'[Parameter Date] ) = "Quarter",
        CALCULATE (
            LASTDATE ( 'Calendar'[Start of Quarter] ),
            ALLSELECTED ( 'Calendar' )
        ),
    MAX ( 'Parameter Date'[Parameter Date] ) = "Year", CALCULATE ( LASTDATE ( 'Calendar'[Start of Year] ), ALLSELECTED ( 'Calendar' ) )
)

'Visual Measure'[Focus Blue] = 
"#344C69"

'Visual Measure'[Items per Order - Sparkline - Card - Product] = 
// Static line color - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)
VAR LineColour = "%23344C69"
VAR PointColour = "%23F9F9F9"
VAR Defs = "<defs>
    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>
        <stop stop-color='#4D6A8D' offset='0' />
        <stop stop-color='#4D6A8D' offset='0.3' />
        <stop stop-color='#F9F9F9' offset='1' />
    </linearGradient>
</defs>" // "Date" field used in this example along the X axis
VAR XMinDate =
    MIN ( 'Calendar'[Start of Month] )
VAR XMaxDate =
    MAX ( 'Calendar'[Start of Month] ) // Obtain overall min and overall max measure values when evaluated for each date
VAR YMinValue =
    MINX ( VALUES ( 'Calendar'[Start of Month] ), CALCULATE ( [Items per Order] ) )
VAR YMaxValue =
    MAXX ( VALUES ( 'Calendar'[Start of Month] ), CALCULATE ( [Items per Order] ) ) // Build table of X & Y coordinates and fit to 50 x 150 viewbox
VAR SparklineTable =
    ADDCOLUMNS (
        SUMMARIZE ( 'Calendar', 'Calendar'[Start of Month] ),
        "X",
            INT (
                150
                    * DIVIDE ( 'Calendar'[Start of Month] - XMinDate, XMaxDate - XMinDate )
            ),
        "Y",
            INT ( 50 * DIVIDE ( [Items per Order] - YMinValue, YMaxValue - YMinValue ) )
    ) // Concatenate X & Y coordinates to build the sparkline
VAR Lines =
    CONCATENATEX (
        SparklineTable,
        [X] & "," & 50 - [Y],
        " ",
        'Calendar'[Start of Month]
    ) // Last data points on the line
VAR LastSparkYValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [Y] )
VAR LastSparkXValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [X] ) // Add to SVG, and verify Data Category is set to Image URL for this measure
VAR SVGImageURL = "data:image/svg+xml;utf8," & --- gradient---
"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>" & Defs & "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' 
      stroke-width='0' points=' 0 50 " & Lines & " 150 150 Z '/>" & --- Lines---
"<polyline 
        fill='transparent' stroke='" & LineColour & "' 
        stroke-linecap='round' stroke-linejoin='round' 
        stroke-width='2' points=' " & Lines & " '/>" & --- Last Point---
"<circle cx='" & LastSparkXValue & "' cy='" & 50 - LastSparkYValue & "' r='4' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" & "</svg>"
RETURN
    SVGImageURL

'Visual Measure'[Items per Order - Subtitle - Card - Product] = 
VAR __Arrow =
    SWITCH (
        TRUE (),
        [LM MOM % Items per Order] > 0, UNICHAR ( 11165 ),
        [LM MOM % Items per Order] < 0, UNICHAR ( 11167 )
    )
VAR __Negative =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Items per Order], "0.00%" ) & " MOM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Positive =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Items per Order], "0.00%" ) & " MOM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Result =
    SWITCH (
        TRUE (),
        ISBLANK ( [LM MOM % Items per Order] ), "-",
        [LM MOM % Items per Order] = 0, "No MoM Change",
        [LM MOM % Items per Order] < 0, __Negative,
        [LM MOM % Items per Order] > 0, __Positive
    )
RETURN
    __Result

'Visual Measure'[Light Blue] = 
"#B8C3D1"

'Visual Measure'[Light Grey] = 
"#C5CACE"

'Visual Measure'[Light Standard Blue] = 
"#94A6BB"

'Visual Measure'[Negative Color] = 
"#A61032"

'Visual Measure'[New Customers - Axis - Line Chart - Customer] = 
VAR __MaxValue =
    SWITCH (
        TRUE (),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Date", MAXX ( VALUES ( 'Calendar'[Date] ), [New Customers (Payments)] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Month", MAXX ( VALUES ( 'Calendar'[Start of Month] ), [New Customers (Payments)] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Quarter", MAXX ( VALUES ( 'Calendar'[Start of Quarter] ), [New Customers (Payments)] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Year", MAXX ( VALUES ( 'Calendar'[Start of Year] ), [New Customers (Payments)] )
    )
VAR __Result = __MaxValue * 1.15
RETURN
    __Result

'Visual Measure'[New Customers - Background Color - Matrix - Retention] = 
VAR __FormattingMode =
    SELECTEDVALUE ( 'Cohort Formatting Mode'[ID] )
VAR __Min =
    CALCULATE (
        MINX (
            CROSSJOIN (
                DISTINCT ( 'Calendar'[Month Year] ),
                DISTINCT ( 'Order'[Months Since First Transaction] )
            ),
            [New Customers]
        ),
        ALLSELECTED ()
    )
VAR __Max =
    CALCULATE (
        MAXX (
            CROSSJOIN (
                DISTINCT ( 'Calendar'[Month Year] ),
                DISTINCT ( 'Order'[Months Since First Transaction] )
            ),
            [New Customers]
        ),
        ALLSELECTED ()
    )
VAR __Min_2 =
    MIN ( __Min, 0 )
VAR __Span = __Max - __Min_2
VAR __Norm =
    DIVIDE ( [New Customers] - __Min_2, __Span )
VAR __Lightness =
    100
        - ROUND ( __Norm * 80, 0 )
VAR __Hue = 210
VAR __Saturation = 45
VAR __Color = "hsla(" & __Hue & "," & __Saturation & "%," & __Lightness & "%," & "0.9)"
VAR __Result =
    SWITCH (
        TRUE (),
        __FormattingMode = 1, __Color,
        __FormattingMode = 2, __Color,
        __FormattingMode = 3, [Transparent Color],
        __Color
    )
RETURN
    __Result

'Visual Measure'[New Customers - Font Color - Matrix - Retention] = 
VAR __FormattingMode =
    SELECTEDVALUE ( 'Cohort Formatting Mode'[ID] )
VAR __Min =
    CALCULATE (
        MINX (
            CROSSJOIN (
                DISTINCT ( 'Calendar'[Month Year] ),
                DISTINCT ( 'Order'[Months Since First Transaction] )
            ),
            [New Customers]
        ),
        ALLSELECTED ()
    )
VAR __Max =
    CALCULATE (
        MAXX (
            CROSSJOIN (
                DISTINCT ( 'Calendar'[Month Year] ),
                DISTINCT ( 'Order'[Months Since First Transaction] )
            ),
            [New Customers]
        ),
        ALLSELECTED ()
    )
VAR __Min_2 =
    MIN ( __Min, 0 )
VAR __Span = __Max - __Min_2
VAR __Norm =
    DIVIDE ( [New Customers] - __Min_2, __Span )
VAR __Lightness =
    100
        - ROUND ( __Norm * 80, 0 )
VAR __FontColor =
    IF ( __Lightness < 56, "#FFFFFF", "#223144" )
VAR __Result =
    SWITCH (
        TRUE (),
        __FormattingMode = 1, __FontColor,
        __FormattingMode = 2, [Transparent Color],
        __FormattingMode = 3, [Standard Blue],
        [Standard Blue]
    )
RETURN
    __Result

'Visual Measure'[New Customers - Label Color - Line Chart - Customer] = 
VAR __CurrentDateParameterValue =
    SWITCH (
        TRUE (),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Date", SELECTEDVALUE ( 'Calendar'[Date] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Month", SELECTEDVALUE ( 'Calendar'[Start of Month] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Quarter", SELECTEDVALUE ( 'Calendar'[Start of Quarter] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Year", SELECTEDVALUE ( 'Calendar'[Start of Year] )
    )
VAR __MaxValue =
    SWITCH (
        TRUE (),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Date", MAXX ( ALLSELECTED ( 'Calendar'[Date] ), [New Customers (Payments)] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Month", MAXX ( ALLSELECTED ( 'Calendar'[Start of Month] ), [New Customers (Payments)] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Quarter",
            MAXX (
                ALLSELECTED ( 'Calendar'[Start of Quarter] ),
                [New Customers (Payments)]
            ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Year", MAXX ( ALLSELECTED ( 'Calendar'[Start of Year] ), [New Customers (Payments)] )
    )
VAR __MinValue =
    SWITCH (
        TRUE (),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Date", MINX ( ALLSELECTED ( 'Calendar'[Date] ), [New Customers (Payments)] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Month", MINX ( ALLSELECTED ( 'Calendar'[Start of Month] ), [New Customers (Payments)] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Quarter",
            MINX (
                ALLSELECTED ( 'Calendar'[Start of Quarter] ),
                [New Customers (Payments)]
            ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Year", MINX ( ALLSELECTED ( 'Calendar'[Start of Year] ), [New Customers (Payments)] )
    )
VAR __Result =
    IF (
        [New Customers (Payments)] = __MaxValue
            || [New Customers (Payments)] = __MinValue
            || __CurrentDateParameterValue = [Start Parameter Date Value]
            || __CurrentDateParameterValue = [End Parameter Date Value],
        [Focus Blue],
        [Transparent Color]
    )
RETURN
    __Result

'Visual Measure'[New Customers - Label Color - Line Chart - Retention] = 
VAR __CurrentDateParameterValue =
    SELECTEDVALUE ( 'Calendar'[Start of Month] )
VAR __MaxValue =
    MAXX ( ALLSELECTED ( 'Calendar'[Start of Month] ), [New Customers] )
VAR __MinValue =
    MINX ( ALLSELECTED ( 'Calendar'[Start of Month] ), [New Customers] )
VAR __StartDateValue =
    CALCULATE (
        FIRSTDATE ( 'Calendar'[Start of Month] ),
        ALLSELECTED ( 'Calendar' )
    )
VAR __EndDateValue =
    CALCULATE (
        LASTDATE ( 'Calendar'[Start of Month] ),
        ALLSELECTED ( 'Calendar' )
    )
VAR __Result =
    IF (
        [New Customers] = __MaxValue
            || [New Customers] = __MinValue
            || __CurrentDateParameterValue = __StartDateValue
            || __CurrentDateParameterValue = __EndDateValue,
        [Focus Blue],
        [Transparent Color]
    )
RETURN
    __Result

'Visual Measure'[New Customers - Title - Line Chart - Customer] = 
"New Customers by " & [Current Parameter Date Granularity]

'Visual Measure'[New Customers Forecast - Axis - Line Chart - Customer] = 
VAR __MaxValue =
    MAXX ( VALUES ( 'Calendar'[Start of Month] ), [New Customers (Payments)] )
VAR __Result = __MaxValue * 1.65
RETURN
    __Result

'Visual Measure'[New Customers Forecast - Label Color - Line Chart - Customer] = 
VAR __MaxValue =
    MAXX ( ALLSELECTED ( 'Calendar'[Start of Month] ), [New Customers (Payments)] )
VAR __MinValue =
    MINX ( ALLSELECTED ( 'Calendar'[Start of Month] ), [New Customers (Payments)] )
VAR __Result =
    IF (
        [New Customers (Payments)] = __MaxValue
            || [New Customers (Payments)] = __MinValue
            || SELECTEDVALUE ( 'Calendar'[Start of Month] ) = [Start Parameter Date Value]
            || SELECTEDVALUE ( 'Calendar'[Start of Month] ) = [End Parameter Date Value],
        [Focus Blue],
        [Transparent Color]
    )
RETURN
    __Result

'Visual Measure'[On-Time Delivery Rate - Sparkline - Card - Product] = 
// Static line color - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)
VAR LineColour = "%23344C69"
VAR PointColour = "%23F9F9F9"
VAR Defs = "<defs>
    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>
        <stop stop-color='#4D6A8D' offset='0' />
        <stop stop-color='#4D6A8D' offset='0.3' />
        <stop stop-color='#F9F9F9' offset='1' />
    </linearGradient>
</defs>" // "Date" field used Total Categories along the X axis
VAR XMinDate =
    MIN ( 'Calendar'[Start of Month] )
VAR XMaxDate =
    MAX ( 'Calendar'[Start of Month] ) // Obtain overall min and overall max measure values when evaluated for each date
VAR YMinValue =
    MINX (
        VALUES ( 'Calendar'[Start of Month] ),
        CALCULATE ( [On-Time Delivery Rate] )
    )
VAR YMaxValue =
    MAXX (
        VALUES ( 'Calendar'[Start of Month] ),
        CALCULATE ( [On-Time Delivery Rate] )
    ) // Build table of X & Y coordinates and fit to 50 x 150 viewbox
VAR SparklineTable =
    ADDCOLUMNS (
        SUMMARIZE ( 'Calendar', 'Calendar'[Start of Month] ),
        "X",
            INT (
                150
                    * DIVIDE ( 'Calendar'[Start of Month] - XMinDate, XMaxDate - XMinDate )
            ),
        "Y",
            INT (
                50
                    * DIVIDE ( [On-Time Delivery Rate] - YMinValue, YMaxValue - YMinValue )
            )
    ) // Concatenate X & Y coordinates to build the sparkline
VAR Lines =
    CONCATENATEX (
        SparklineTable,
        [X] & "," & 50 - [Y],
        " ",
        'Calendar'[Start of Month]
    ) // Last data points on the line
VAR LastSparkYValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [Y] )
VAR LastSparkXValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [X] ) // Add to SVG, and verify Data Category is set to Image URL for this measure
VAR SVGImageURL = "data:image/svg+xml;utf8," & --- gradient---
"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>" & Defs & "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' 
      stroke-width='0' points=' 0 50 " & Lines & " 150 150 Z '/>" & --- Lines---
"<polyline 
        fill='transparent' stroke='" & LineColour & "' 
        stroke-linecap='round' stroke-linejoin='round' 
        stroke-width='2' points=' " & Lines & " '/>" & --- Last Point---
"<circle cx='" & LastSparkXValue & "' cy='" & 50 - LastSparkYValue & "' r='4' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" & "</svg>"
RETURN
    SVGImageURL

'Visual Measure'[On-Time Delivery Rate - Subtitle - Card - Sales] = 
VAR __Arrow =
    SWITCH (
        TRUE (),
        [LM MOM % On-Time Delivery Rate] > 0, UNICHAR ( 11165 ),
        [LM MOM % On-Time Delivery Rate] < 0, UNICHAR ( 11167 )
    )
VAR __Negative =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % On-Time Delivery Rate], "0.00%" ) & " MoM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Positive =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % On-Time Delivery Rate], "0.00%" ) & " MoM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Result =
    SWITCH (
        TRUE (),
        ISBLANK ( [LM MOM % On-Time Delivery Rate] ), "-",
        [LM MOM % On-Time Delivery Rate] = 0, "No MoM Change",
        [LM MOM % On-Time Delivery Rate] < 0, __Negative,
        [LM MOM % On-Time Delivery Rate] > 0, __Positive
    )
RETURN
    __Result

'Visual Measure'[On-Time Delivery Rate - Title Color - Card - Sales] = 
SWITCH (
    TRUE (),
    [LM MOM % On-Time Delivery Rate] > 0, [Positive Color],
    [LM MOM % On-Time Delivery Rate] < 0, [Negative Color]
)

'Visual Measure'[Order Cancellation Rate - Sparkline - Card - Sales] = 
// Static line color - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)
VAR LineColour = "%23344C69"
VAR PointColour = "%23F9F9F9"
VAR Defs = "<defs>
    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>
        <stop stop-color='#4D6A8D' offset='0' />
        <stop stop-color='#4D6A8D' offset='0.3' />
        <stop stop-color='#F9F9F9' offset='1' />
    </linearGradient>
</defs>" // "Date" field used in this example along the X axis
VAR XMinDate =
    MIN ( 'Calendar'[Start of Month] )
VAR XMaxDate =
    MAX ( 'Calendar'[Start of Month] ) // Obtain overall min and overall max measure values when evaluated for each date
VAR YMinValue =
    MINX (
        VALUES ( 'Calendar'[Start of Month] ),
        CALCULATE ( [Average Order Cancellation Rate] )
    )
VAR YMaxValue =
    MAXX (
        VALUES ( 'Calendar'[Start of Month] ),
        CALCULATE ( [Average Order Cancellation Rate] )
    ) // Build table of X & Y coordinates and fit to 50 x 150 viewbox
VAR SparklineTable =
    ADDCOLUMNS (
        SUMMARIZE ( 'Calendar', 'Calendar'[Start of Month] ),
        "X",
            INT (
                150
                    * DIVIDE ( 'Calendar'[Start of Month] - XMinDate, XMaxDate - XMinDate )
            ),
        "Y",
            INT (
                50
                    * DIVIDE ( [Average Order Cancellation Rate] - YMinValue, YMaxValue - YMinValue )
            )
    ) // Concatenate X & Y coordinates to build the sparkline
VAR Lines =
    CONCATENATEX (
        SparklineTable,
        [X] & "," & 50 - [Y],
        " ",
        'Calendar'[Start of Month]
    ) // Last data points on the line
VAR LastSparkYValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [Y] )
VAR LastSparkXValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [X] ) // Add to SVG, and verify Data Category is set to Image URL for this measure
VAR SVGImageURL = "data:image/svg+xml;utf8," & --- gradient---
"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>" & Defs & "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' 
      stroke-width='0' points=' 0 50 " & Lines & " 150 150 Z '/>" & --- Lines---
"<polyline 
        fill='transparent' stroke='" & LineColour & "' 
        stroke-linecap='round' stroke-linejoin='round' 
        stroke-width='2' points=' " & Lines & " '/>" & --- Last Point---
"<circle cx='" & LastSparkXValue & "' cy='" & 50 - LastSparkYValue & "' r='4' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" & "</svg>"
RETURN
    SVGImageURL

'Visual Measure'[Payment Rank Title - Payment - Tooltip - Customer] = 
VAR __Current =
    SELECTEDVALUE ( 'Payment Type'[Payment Type] )
VAR __SelectedMetric = [Total Orders (Payments)]
VAR __Rank =
    RANKX ( ALL ( 'Payment Type' ), [Total Orders (Payments)],, DESC, DENSE )
VAR __Result = __Current & " (Rank " & __Rank & ")"
RETURN
    __Result

'Visual Measure'[Payment Type - Axis - Tornado Chart - Customer] = 
VAR __MaxValue =
    MAXX ( ALLSELECTED ( 'Payment Type'[Payment Type] ), [Total Orders (Payments)] )
VAR __Result = __MaxValue * 1.2
RETURN
    __Result

'Visual Measure'[Payment Type AOV - Description - Column Chart - Customer] = 
VAR __AverageOrderValue =
    FORMAT ( [Average Order Value (AOV)], "#,0.00 R$" )
VAR __Result =
    "AOV:" & REPT ( " ", 2 ) & __AverageOrderValue
RETURN
    __Result

'Visual Measure'[Payment Type AOV Inv - Axis - Tornado Chart - Customer] = 
VAR __MinValue =
    MINX (
        ALLSELECTED ( 'Payment Type'[Payment Type] ),
        [Average Order Value (AOV) Inverted]
    )
VAR __Result = __MinValue * 1.2
RETURN
    __Result

'Visual Measure'[Payment Type Orders - Description - Column Chart - Customer] = 
VAR __Orders =
    // FORMAT(ROUND(DIVIDE([Total Orders (Payments)], 1000, 0), 0), "#,0") & "k"
    FORMAT (
        [Total Orders (Payments)],
        "# ###"
    )
VAR __Result =
    "Orders:" & REPT ( " ", 2 ) & __Orders
RETURN
    __Result

'Visual Measure'[Positive Color] = 
"#00997A"

'Visual Measure'[Product Metric - Axis - Pareto Category - Product] = 
VAR __MaxValue =
    MAXX ( VALUES ( Category[Category Name] ), [Selected Product Metric] )
VAR __Result = __MaxValue * 1.15
RETURN
    __Result

'Visual Measure'[Product Metric - Axis - Scatter Product - Product] = 
VAR __MaxValue =
    SWITCH (
        TRUE (),
        MAX ( 'Product Category Field'[Product Category Field] ) = "Product", MAXX ( VALUES ( 'Product'[Product Id] ), [Selected Product Metric] ),
        MAX ( 'Product Category Field'[Product Category Field] ) = "Category", MAXX ( VALUES ( Category[Category Name] ), [Selected Product Metric] )
    )
VAR __Result = __MaxValue * 1.15
RETURN
    __Result

'Visual Measure'[Product Metric - Description - Pareto Category - Product] = 
VAR __SelectedMetric =
    SWITCH (
        TRUE (),
        MAX ( 'Product Metric'[Product Metric] ) = "Revenue", "Revenues",
        MAX ( 'Product Metric'[Product Metric] ) = "Units Sold", "Units Sold"
    )
VAR __CategoriesNumber =
    IF (
        [Product Metric Pareto Cutoff Rank - Pareto Category - Product] > 12,
        "over 12",
        [Product Metric Pareto Cutoff Rank - Pareto Category - Product]
    )
VAR __Result = " of " & __SelectedMetric & " comes from " & __CategoriesNumber & " Categories"
RETURN
    __Result

'Visual Measure'[Product Metric - Subtitle - Pareto Category - Product] = 
VAR __Result =
    SWITCH (
        TRUE (),
        MAX ( 'Product Metric'[Product Metric] ) = "Revenue", "Revenues in mBRL, in % | Cumulative Revenues in %",
        MAX ( 'Product Metric'[Product Metric] ) = "Units Sold", "Units Sold in '000, in % | Cumulative Orders in %"
    )
RETURN
    __Result

'Visual Measure'[Product Metric - Title - Pareto Category - Product] = 
VAR __SelectedMetric =
    SWITCH (
        TRUE (),
        MAX ( 'Product Metric'[Product Metric] ) = "Revenue", "Revenue",
        MAX ( 'Product Metric'[Product Metric] ) = "Units Sold", "Units Sold"
    )
VAR __Result = "Top 12 Categories by " & __SelectedMetric & " Contribution (Pareto Analysis)"
RETURN
    __Result

'Visual Measure'[Product Metric - Title - Scatter Product - Product] = 
VAR __SelectedMetric =
    SWITCH (
        TRUE (),
        MAX ( 'Product Metric'[Product Metric] ) = "Revenue", "Revenue",
        MAX ( 'Product Metric'[Product Metric] ) = "Units Sold", "Units Sold"
    )
VAR __Result =
    SWITCH (
        TRUE (),
        MAX ( 'Product Category Field'[Product Category Field] ) = "Product",
            "Total " & __SelectedMetric & " vs. Product Rating (Highlighting Top 20 Products and Low Ratings)",
        MAX ( 'Product Category Field'[Product Category Field] ) = "Category",
            "Total " & __SelectedMetric & " vs. Category Rating (Highlighting Top 20 Categories and Low Ratings)"
    )
RETURN
    __Result

'Visual Measure'[Product Metric GT% - Pareto Category - Product] = 
DIVIDE (
    [Selected Product Metric],
    [Total Product Metric - Pareto Category - Product],
    0
)

'Visual Measure'[Product Metric Pareto Color - Pareto Category - Product] = 
IF (
    [Product Metric Rank - Pareto Category - Product] > [Product Metric Pareto Cutoff Rank - Pareto Category - Product],
    [Light Grey],
    [Light Standard Blue]
)

'Visual Measure'[Product Metric Pareto Cutoff Rank - Pareto Category - Product] = 
CALCULATE (
    MAXX (
        VALUES ( Category[Category Name] ),
        [Cutoff Product Metric Rank - Pareto Category - Product]
    ),
    ALLSELECTED ( Category )
)

'Visual Measure'[Product Metric Pareto Label Color - Pareto Category - Product] = 
IF (
    [Product Metric Rank - Pareto Category - Product] > [Product Metric Pareto Cutoff Rank - Pareto Category - Product],
    [Light Grey],
    [Focus Blue]
)

'Visual Measure'[Product Metric Rank - Pareto Category - Product] = 
IF (
    ISINSCOPE ( Category[Category Name] ),
    RANKX ( ALLSELECTED ( Category[Category Name] ), [Selected Product Metric] )
)

'Visual Measure'[Product Metric Trend Title - Tooltip - Product] = 
VAR __SelectedMetric =
    SWITCH (
        TRUE (),
        MAX ( 'Product Metric'[Product Metric] ) = "Revenue", "Revenue",
        MAX ( 'Product Metric'[Product Metric] ) = "Units Sold", "Units Sold"
    )
VAR __Result = "Monthly " & __SelectedMetric & " Trend"
RETURN
    __Result

'Visual Measure'[Product Rank Title - Product - Tooltip - Product] = 
VAR __Current =
    SWITCH (
        TRUE (),
        MAX ( 'Product Category Field'[Product Category Field] ) = "Product", SELECTEDVALUE ( 'Product'[Product Id] ),
        MAX ( 'Product Category Field'[Product Category Field] ) = "Category", SELECTEDVALUE ( Category[Category Name] )
    )
VAR __Rank =
    SWITCH (
        TRUE (),
        MAX ( 'Product Category Field'[Product Category Field] ) = "Product", RANKX ( ALL ( 'Product' ), [Selected Product Metric],, DESC, DENSE ),
        MAX ( 'Product Category Field'[Product Category Field] ) = "Category", RANKX ( ALL ( Category ), [Selected Product Metric],, DESC, DENSE )
    )
VAR __Result =
    SWITCH (
        TRUE (),
        MAX ( 'Product Category Field'[Product Category Field] ) = "Product",
            "Product " & __Current & " (Rank " & __Rank & ")",
        MAX ( 'Product Category Field'[Product Category Field] ) = "Category",
            __Current & " (Rank " & __Rank & ")"
    )
RETURN
    __Result

'Visual Measure'[Product Rating - Description - Scatter Product - Product] = 
VAR __WithRatingBelow25 =
    SWITCH (
        TRUE (),
        MAX ( 'Product Category Field'[Product Category Field] ) = "Product", CALCULATE ( [Total Products], 'Product'[Product Rating] < 2.5 ),
        MAX ( 'Product Category Field'[Product Category Field] ) = "Category",
            COUNTROWS (
                FILTER (
                    SUMMARIZE (
                        Category,
                        Category[Category Name],
                        "Average Rating", AVERAGE ( Product[Product Rating] )
                    ),
                    [Average Rating] < 2.5
                )
            )
    )
VAR __WithRatingBelow25Pct =
    SWITCH (
        TRUE (),
        MAX ( 'Product Category Field'[Product Category Field] ) = "Product", DIVIDE ( __WithRatingBelow25, [Total Products] ),
        MAX ( 'Product Category Field'[Product Category Field] ) = "Category", DIVIDE ( __WithRatingBelow25, [Total Categories] )
    )
VAR __SelectedField =
    SWITCH (
        TRUE (),
        MAX ( 'Product Category Field'[Product Category Field] ) = "Product", "Products",
        MAX ( 'Product Category Field'[Product Category Field] ) = "Category", "Categories"
    )
VAR __Result =
    IF (
        __WithRatingBelow25 = 0,
        "No " & __SelectedField & " with rating below 2.5",
        FORMAT ( __WithRatingBelow25Pct, "0.0%" ) & " of " & __SelectedField & " have a rating below 2.5"
    )
RETURN
    __Result

'Visual Measure'[Product Rating - Marker Color - Scatter Product - Product] = 
VAR __ProductRating =
    AVERAGE ( 'Product'[Product Rating] )
VAR __ProductMetricRank =
    SWITCH (
        TRUE (),
        MAX ( 'Product Category Field'[Product Category Field] ) = "Product",
            IF (
                ISINSCOPE ( 'Product'[Product Id] ),
                RANKX ( ALLSELECTED ( 'Product'[Product Id] ), [Selected Product Metric] )
            ),
        MAX ( 'Product Category Field'[Product Category Field] ) = "Category",
            IF (
                ISINSCOPE ( Category[Category Name] ),
                RANKX ( ALLSELECTED ( Category[Category Name] ), [Selected Product Metric] )
            )
    )
VAR __Result =
    SWITCH (
        TRUE (),
        __ProductMetricRank <= 20
            && __ProductRating < 2.5, [Semi Negative Color],
        __ProductMetricRank <= 20, [Focus Blue],
        __ProductRating < 2.5, [Negative Color],
        [Light Grey]
    )
RETURN
    __Result

'Visual Measure'[Product Rating - Reference Line - Scatter Product - Product] = 
VAR __Rank20ProductOrCategory =
    SWITCH (
        TRUE (),
        MAX ( 'Product Category Field'[Product Category Field] ) = "Product",
            CALCULATE (
                MAX ( 'Product'[Product Id] ),
                FILTER (
                    ALLSELECTED ( 'Product'[Product Id] ),
                    RANKX ( ALLSELECTED ( 'Product'[Product Id] ), [Selected Product Metric] ) = 20
                )
            ),
        MAX ( 'Product Category Field'[Product Category Field] ) = "Category",
            CALCULATE (
                MAX ( Category[Category Name] ),
                FILTER (
                    ALLSELECTED ( Category[Category Name] ),
                    RANKX ( ALLSELECTED ( Category[Category Name] ), [Selected Product Metric] ) = 20
                )
            )
    )
VAR __Result =
    SWITCH (
        TRUE (),
        MAX ( 'Product Category Field'[Product Category Field] ) = "Product",
            CALCULATE (
                [Selected Product Metric],
                'Product'[Product Id] = __Rank20ProductOrCategory
            ),
        MAX ( 'Product Category Field'[Product Category Field] ) = "Category",
            CALCULATE (
                [Selected Product Metric],
                Category[Category Name] = __Rank20ProductOrCategory
            )
    )
RETURN
    __Result

'Visual Measure'[Recovered Customers - Label Color - Line Chart - Retention] = 
VAR __CurrentDateParameterValue =
    SELECTEDVALUE ( 'Calendar'[Start of Month] )
VAR __MaxValue =
    MAXX ( ALLSELECTED ( 'Calendar'[Start of Month] ), [Recovered Customers] )
VAR __MinValue =
    MINX ( ALLSELECTED ( 'Calendar'[Start of Month] ), [Recovered Customers] )
VAR __StartDateValue =
    CALCULATE (
        FIRSTDATE ( 'Calendar'[Start of Month] ),
        ALLSELECTED ( 'Calendar' )
    )
VAR __EndDateValue =
    CALCULATE (
        LASTDATE ( 'Calendar'[Start of Month] ),
        ALLSELECTED ( 'Calendar' )
    )
VAR __Result =
    IF (
        [Recovered Customers] = __MaxValue
            || [Recovered Customers] = __MinValue
            || __CurrentDateParameterValue = __StartDateValue
            || __CurrentDateParameterValue = __EndDateValue,
        [Focus Blue],
        [Transparent Color]
    )
RETURN
    __Result

'Visual Measure'[Retention Rate - Sparkline - Card - Customer] = 
// Static line color - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)
VAR LineColour = "%23344C69"
VAR PointColour = "%23F9F9F9"
VAR Defs = "<defs>
    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>
        <stop stop-color='#4D6A8D' offset='0' />
        <stop stop-color='#4D6A8D' offset='0.3' />
        <stop stop-color='#F9F9F9' offset='1' />
    </linearGradient>
</defs>" // "Date" field used in this example along the X axis
VAR XMinDate =
    MIN ( 'Calendar'[Start of Month] )
VAR XMaxDate =
    MAX ( 'Calendar'[Start of Month] ) // Obtain overall min and overall max measure values when evaluated for each date
VAR YMinValue =
    MINX ( VALUES ( 'Calendar'[Start of Month] ), CALCULATE ( [Retention Rate] ) )
VAR YMaxValue =
    MAXX ( VALUES ( 'Calendar'[Start of Month] ), CALCULATE ( [Retention Rate] ) ) // Build table of X & Y coordinates and fit to 50 x 150 viewbox
VAR SparklineTable =
    ADDCOLUMNS (
        SUMMARIZE ( 'Calendar', 'Calendar'[Start of Month] ),
        "X",
            INT (
                150
                    * DIVIDE ( 'Calendar'[Start of Month] - XMinDate, XMaxDate - XMinDate )
            ),
        "Y",
            INT ( 50 * DIVIDE ( [Retention Rate] - YMinValue, YMaxValue - YMinValue ) )
    ) // Concatenate X & Y coordinates to build the sparkline
VAR Lines =
    CONCATENATEX (
        SparklineTable,
        [X] & "," & 50 - [Y],
        " ",
        'Calendar'[Start of Month]
    ) // Last data points on the line
VAR LastSparkYValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [Y] )
VAR LastSparkXValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [X] ) // Add to SVG, and verify Data Category is set to Image URL for this measure
VAR SVGImageURL = "data:image/svg+xml;utf8," & --- gradient---
"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>" & Defs & "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' 
      stroke-width='0' points=' 0 50 " & Lines & " 150 150 Z '/>" & --- Lines---
"<polyline 
        fill='transparent' stroke='" & LineColour & "' 
        stroke-linecap='round' stroke-linejoin='round' 
        stroke-width='2' points=' " & Lines & " '/>" & --- Last Point---
"<circle cx='" & LastSparkXValue & "' cy='" & 50 - LastSparkYValue & "' r='4' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" & "</svg>"
RETURN
    SVGImageURL

'Visual Measure'[Returning & Recovered Customers - Axis - Line Chart - Retention] = 
VAR __MaxValue =
    MAXX (
        VALUES ( 'Calendar'[Start of Month] ),
        [Recovered & Returning Customers]
    )
VAR __Result = __MaxValue * 1.15
RETURN
    __Result

'Visual Measure'[Returning Customers - Label Color - Line Chart - Retention] = 
VAR __CurrentDateParameterValue =
    SELECTEDVALUE ( 'Calendar'[Start of Month] )
VAR __MaxValue =
    MAXX ( ALLSELECTED ( 'Calendar'[Start of Month] ), [Returning Customers] )
VAR __MinValue =
    MINX ( ALLSELECTED ( 'Calendar'[Start of Month] ), [Returning Customers] )
VAR __StartDateValue =
    CALCULATE (
        FIRSTDATE ( 'Calendar'[Start of Month] ),
        ALLSELECTED ( 'Calendar' )
    )
VAR __EndDateValue =
    CALCULATE (
        LASTDATE ( 'Calendar'[Start of Month] ),
        ALLSELECTED ( 'Calendar' )
    )
VAR __Result =
    IF (
        [Returning Customers] = __MaxValue
            || [Returning Customers] = __MinValue
            || __CurrentDateParameterValue = __StartDateValue
            || __CurrentDateParameterValue = __EndDateValue,
        [Focus Blue],
        [Transparent Color]
    )
RETURN
    __Result

'Visual Measure'[Review Score - Title - Area Chart - Product] = 
"Order Review Scores by " & [Current Parameter Date Granularity]

'Visual Measure'[Sales Metric - Axis - Line Chart - Sales] = 
VAR __MaxValue =
    SWITCH (
        TRUE (),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Date", MAXX ( VALUES ( 'Calendar'[Date] ), [Selected Sales Metric] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Month", MAXX ( VALUES ( 'Calendar'[Start of Month] ), [Selected Sales Metric] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Quarter", MAXX ( VALUES ( 'Calendar'[Start of Quarter] ), [Selected Sales Metric] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Year", MAXX ( VALUES ( 'Calendar'[Start of Year] ), [Selected Sales Metric] )
    )
VAR __Result = __MaxValue * 1.15
RETURN
    __Result

'Visual Measure'[Sales Metric - Axis - Pareto Seller - Sales] = 
VAR __MaxValue =
    MAXX ( VALUES ( Seller[Seller Id] ), [Selected Sales Metric] )
VAR __Result = __MaxValue * 1.15
RETURN
    __Result

'Visual Measure'[Sales Metric - Description - Pareto Seller - Sales] = 
VAR __SelectedMetric =
    SWITCH (
        TRUE (),
        MAX ( 'Sales Metric'[Sales Metric] ) = "Revenue", "Revenues",
        MAX ( 'Sales Metric'[Sales Metric] ) = "Orders", "Orders"
    )
VAR __SellersNumber =
    IF (
        [Sales Metric Pareto Cutoff Rank - Pareto Seller - Sales] > 20,
        "over 20",
        [Sales Metric Pareto Cutoff Rank - Pareto Seller - Sales]
    )
VAR __Result = " of " & __SelectedMetric & " comes from " & __SellersNumber & " Sellers"
RETURN
    __Result

'Visual Measure'[Sales Metric - Label Color - Line Chart - Sales] = 
VAR __CurrentDateParameterValue =
    SWITCH (
        TRUE (),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Date", SELECTEDVALUE ( 'Calendar'[Date] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Month", SELECTEDVALUE ( 'Calendar'[Start of Month] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Quarter", SELECTEDVALUE ( 'Calendar'[Start of Quarter] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Year", SELECTEDVALUE ( 'Calendar'[Start of Year] )
    )
VAR __MaxValue =
    SWITCH (
        TRUE (),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Date", MAXX ( ALLSELECTED ( 'Calendar'[Date] ), [Selected Sales Metric] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Month", MAXX ( ALLSELECTED ( 'Calendar'[Start of Month] ), [Selected Sales Metric] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Quarter", MAXX ( ALLSELECTED ( 'Calendar'[Start of Quarter] ), [Selected Sales Metric] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Year", MAXX ( ALLSELECTED ( 'Calendar'[Start of Year] ), [Selected Sales Metric] )
    )
VAR __MinValue =
    SWITCH (
        TRUE (),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Date", MINX ( ALLSELECTED ( 'Calendar'[Date] ), [Selected Sales Metric] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Month", MINX ( ALLSELECTED ( 'Calendar'[Start of Month] ), [Selected Sales Metric] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Quarter", MINX ( ALLSELECTED ( 'Calendar'[Start of Quarter] ), [Selected Sales Metric] ),
        MAX ( 'Parameter Date'[Parameter Date] ) = "Year", MINX ( ALLSELECTED ( 'Calendar'[Start of Year] ), [Selected Sales Metric] )
    )
VAR __Result =
    IF (
        [Selected Sales Metric] = __MaxValue
            || [Selected Sales Metric] = __MinValue
            || __CurrentDateParameterValue = [Start Parameter Date Value]
            || __CurrentDateParameterValue = [End Parameter Date Value],
        [Focus Blue],
        [Transparent Color]
    )
RETURN
    __Result

'Visual Measure'[Sales Metric - Subtitle - Pareto Seller - Sales] = 
VAR __Result =
    SWITCH (
        TRUE (),
        MAX ( 'Sales Metric'[Sales Metric] ) = "Revenue", "Revenues in mBRL, in % | Cumulative Revenues in %",
        MAX ( 'Sales Metric'[Sales Metric] ) = "Orders", "Orders in ', in % | Cumulative Orders in %"
    )
RETURN
    __Result

'Visual Measure'[Sales Metric - Title - Line Chart - Sales] = 
VAR __SelectedMetric =
    SWITCH (
        TRUE (),
        MAX ( 'Sales Metric'[Sales Metric] ) = "Revenue", "Revenue",
        MAX ( 'Sales Metric'[Sales Metric] ) = "Orders", "Orders"
    )
VAR __Result = "Total " & __SelectedMetric & " by " & [Current Parameter Date Granularity]
RETURN
    __Result

'Visual Measure'[Sales Metric - Title - Pareto Seller - Sales] = 
VAR __SelectedMetric =
    SWITCH (
        TRUE (),
        MAX ( 'Sales Metric'[Sales Metric] ) = "Revenue", "Revenue",
        MAX ( 'Sales Metric'[Sales Metric] ) = "Orders", "Orders"
    )
VAR __Result = "Top 20 Sellers contributing the most to Total " & __SelectedMetric & ", with cumulative percentages shown by the line."
RETURN
    __Result

'Visual Measure'[Sales Metric Forecast - Axis - Line Chart - Sales] = 
VAR __MaxValue =
    MAXX ( VALUES ( 'Calendar'[Start of Month] ), [Selected Sales Metric] )
VAR __Result = __MaxValue * 1.65
RETURN
    __Result

'Visual Measure'[Sales Metric Forecast - Label Color - Line Chart - Sales] = 
VAR __MaxValue =
    MAXX ( ALLSELECTED ( 'Calendar'[Start of Month] ), [Selected Sales Metric] )
VAR __MinValue =
    MINX ( ALLSELECTED ( 'Calendar'[Start of Month] ), [Selected Sales Metric] )
VAR __Result =
    IF (
        [Selected Sales Metric] = __MaxValue
            || [Selected Sales Metric] = __MinValue
            || SELECTEDVALUE ( 'Calendar'[Start of Month] ) = [Start Parameter Date Value]
            || SELECTEDVALUE ( 'Calendar'[Start of Month] ) = [End Parameter Date Value],
        [Focus Blue],
        [Transparent Color]
    )
RETURN
    __Result

'Visual Measure'[Sales Metric GT% - Pareto Seller - Sales] = 
DIVIDE (
    [Selected Sales Metric],
    [Total Sales Metric - Pareto Seller - Sales],
    0
)

'Visual Measure'[Sales Metric Pareto Color - Pareto Seller - Sales] = 
IF (
    [Sales Metric Rank - Pareto Seller - Sales] > [Sales Metric Pareto Cutoff Rank - Pareto Seller - Sales],
    [Light Grey],
    [Light Standard Blue]
)

'Visual Measure'[Sales Metric Pareto Cutoff Rank - Pareto Seller - Sales] = 
CALCULATE (
    MAXX (
        VALUES ( Seller[Seller Id] ),
        [Cutoff Sales Metric Rank - Pareto Seller - Sales]
    ),
    ALLSELECTED ( Seller )
)

'Visual Measure'[Sales Metric Pareto Label Color - Pareto Seller - Sales] = 
IF (
    [Sales Metric Rank - Pareto Seller - Sales] > [Sales Metric Pareto Cutoff Rank - Pareto Seller - Sales],
    [Light Grey],
    [Focus Blue]
)

'Visual Measure'[Sales Metric Rank - Pareto Seller - Sales] = 
IF (
    ISINSCOPE ( Seller[Seller Id] ),
    RANKX ( ALLSELECTED ( Seller[Seller Id] ), [Selected Sales Metric] )
)

'Visual Measure'[Sales Metric State - Axis - Bar State - Sales] = 
VAR __MaxValue =
    MAXX ( ALLSELECTED ( State[State] ), [Selected Sales Metric] )
VAR __Result = __MaxValue * 1.2
RETURN
    __Result

'Visual Measure'[Sales Metric State - Bar Color - Bar State - Sales] = 
VAR __StateRank =
    IF (
        ISINSCOPE ( State[State] ),
        RANKX ( ALLSELECTED ( State[State] ), [Selected Sales Metric] )
    )
VAR __Result =
    IF ( __StateRank <= 3, [Focus Blue], [Light Grey] )
RETURN
    __Result

'Visual Measure'[Sales Metric State - Label Color - Bar State - Sales] = 
VAR __StateRank =
    IF (
        ISINSCOPE ( State[State] ),
        RANKX ( ALLSELECTED ( State[State] ), [Selected Sales Metric] )
    )
VAR __Result =
    IF ( __StateRank <= 3, [Focus Blue], [Transparent Color] )
RETURN
    __Result

'Visual Measure'[Sales Metric State - Title - Bar State - Sales] = 
VAR __SelectedMetric =
    SWITCH (
        TRUE (),
        MAX ( 'Sales Metric'[Sales Metric] ) = "Revenue", "Revenue",
        MAX ( 'Sales Metric'[Sales Metric] ) = "Orders", "Orders"
    )
VAR __Result = "Total " & __SelectedMetric & " Distribution by State"
RETURN
    __Result

'Visual Measure'[Sales Metric Trend Title - Tooltip - Sales] = 
VAR __SelectedMetric =
    SWITCH (
        TRUE (),
        MAX ( 'Sales Metric'[Sales Metric] ) = "Revenue", "Revenue",
        MAX ( 'Sales Metric'[Sales Metric] ) = "Orders", "Orders"
    )
VAR __Result = "Monthly " & __SelectedMetric & " Trend"
RETURN
    __Result

'Visual Measure'[Selected Cohort Metric] = 
SWITCH (
    TRUE (),
    MAX ( 'Cohort Metric'[Cohort Metric] ) = "Cohort Performance", [Cohort Performance],
    MAX ( 'Cohort Metric'[Cohort Metric] ) = "Retention Rate", [Retention Rate]
)

'Visual Measure'[Selected Date Range] = 
VAR __MinDate =
    FORMAT ( MIN ( 'Calendar'[Date] ), "mmm'yy" )
VAR __MaxDate =
    FORMAT ( MAX ( 'Calendar'[Date] ), "mmm'yy" )
VAR __MinDate2 =
    MIN ( 'Calendar'[Date] )
VAR __MaxDate2 =
    MAX ( 'Calendar'[Date] )
VAR __TotalMonths =
    DATEDIFF ( __MinDate2, __MaxDate2, MONTH ) + 1
VAR __SelectedMonthsCount =
    COUNTROWS ( VALUES ( 'Calendar'[Month Year] ) )
VAR __Result =
    SWITCH (
        TRUE (),
        __MaxDate = __MinDate, __MaxDate,
        __TotalMonths <> __SelectedMonthsCount, "Multiple periods",
        __MinDate & " - " & __MaxDate
    )
RETURN
    __Result

'Visual Measure'[Selected Delivery Metric] = 
SWITCH (
    TRUE (),
    MAX ( 'Delivery Metric'[Delivery Metric] ) = "Total", [Average Total Delivery Time (h)],
    MAX ( 'Delivery Metric'[Delivery Metric] ) = "Approval", [Average Approval Time (h)],
    MAX ( 'Delivery Metric'[Delivery Metric] ) = "Carrier", [Average Carrier Delivery Time (h)],
    MAX ( 'Delivery Metric'[Delivery Metric] ) = "Customer", [Average Customer Delivery Time (h)]
)

'Visual Measure'[Selected Product Metric] = 
SWITCH (
    TRUE (),
    MAX ( 'Product Metric'[Product Metric] ) = "Revenue", [Total Revenue (Payments)],
    MAX ( 'Product Metric'[Product Metric] ) = "Units Sold", [Total Ordered Products]
)

'Visual Measure'[Selected Sales Metric] = 
SWITCH (
    TRUE (),
    MAX ( 'Sales Metric'[Sales Metric] ) = "Revenue", [Total Revenue (Payments)],
    MAX ( 'Sales Metric'[Sales Metric] ) = "Orders", [Total Orders]
)

'Visual Measure'[Seller Rank Title - Seller - Tooltip - Sales] = 
VAR __Current =
    SELECTEDVALUE ( Seller[Seller Id] )
VAR __Rank =
    RANKX ( ALL ( Seller ), [Selected Sales Metric],, DESC, DENSE )
VAR __Result = "Seller " & __Current & " (Rank " & __Rank & ")"
RETURN
    __Result

'Visual Measure'[Seller Rating - Description - Scatter Seller - Sales] = 
VAR __SellersWithRatingBelow25 =
    CALCULATE ( [Total Sellers], Seller[Seller Rating] < 2.5 )
VAR __SellersWithRatingBelow25Pct =
    DIVIDE ( __SellersWithRatingBelow25, [Total Sellers] )
VAR __Result =
    IF (
        __SellersWithRatingBelow25 = 0,
        "No Sellers with rating below 2.5",
        FORMAT ( __SellersWithRatingBelow25Pct, "0.0%" ) & " of Sellers have a rating below 2.5"
    )
RETURN
    __Result

'Visual Measure'[Seller Rating - Marker Color - Scatter Seller - Sales] = 
VAR __SellerRating =
    SELECTEDVALUE ( Seller[Seller Rating] )
VAR __SellerSalesMetricRank =
    IF (
        ISINSCOPE ( Seller[Seller Id] ),
        RANKX ( ALLSELECTED ( Seller[Seller Id] ), [Selected Sales Metric] )
    )
VAR __Result =
    SWITCH (
        TRUE (),
        __SellerSalesMetricRank <= 20
            && __SellerRating < 2.5, [Semi Negative Color],
        __SellerSalesMetricRank <= 20, [Focus Blue],
        __SellerRating < 2.5, [Negative Color],
        [Light Grey]
    )
RETURN
    __Result

'Visual Measure'[Seller Rating - Reference Line - Scatter Seller - Sales] = 
VAR __Rank20Seller =
    CALCULATE (
        MAX ( Seller[Seller Id] ),
        FILTER (
            ALLSELECTED ( Seller[Seller Id] ),
            RANKX ( ALLSELECTED ( Seller[Seller Id] ), [Selected Sales Metric] ) = 20
        )
    )
VAR __Result =
    CALCULATE ( [Selected Sales Metric], Seller[Seller Id] = __Rank20Seller )
RETURN
    __Result

'Visual Measure'[Seller Rating - Title - Scatter Seller - Sales] = 
VAR __SelectedMetric =
    SWITCH (
        TRUE (),
        MAX ( 'Sales Metric'[Sales Metric] ) = "Revenue", "Revenue",
        MAX ( 'Sales Metric'[Sales Metric] ) = "Orders", "Orders"
    )
VAR __Result = "Total " & __SelectedMetric & "  vs. Seller Rating (Highlighting Top 20 Sellers and Low Ratings)"
RETURN
    __Result

'Visual Measure'[Semi Negative Color] = 
"#E05600"

'Visual Measure'[Standard Blue] = 
"#4D6A8D"

'Visual Measure'[Standard Grey] = 
"#6D7A84"

'Visual Measure'[Start Parameter Date Value] = 
SWITCH (
    TRUE (),
    MAX ( 'Parameter Date'[Parameter Date] ) = "Date", CALCULATE ( FIRSTDATE ( 'Calendar'[Date] ), ALLSELECTED ( 'Calendar' ) ),
    MAX ( 'Parameter Date'[Parameter Date] ) = "Month",
        CALCULATE (
            FIRSTDATE ( 'Calendar'[Start of Month] ),
            ALLSELECTED ( 'Calendar' )
        ),
    MAX ( 'Parameter Date'[Parameter Date] ) = "Quarter",
        CALCULATE (
            FIRSTDATE ( 'Calendar'[Start of Quarter] ),
            ALLSELECTED ( 'Calendar' )
        ),
    MAX ( 'Parameter Date'[Parameter Date] ) = "Year",
        CALCULATE (
            FIRSTDATE ( 'Calendar'[Start of Year] ),
            ALLSELECTED ( 'Calendar' )
        )
)

'Visual Measure'[State Rank Title - State - Tooltip - Customer] = 
VAR __Current =
    SELECTEDVALUE ( State[State] )
VAR __SelectedMetric = [Total Customers (Payments)]
VAR __Rank =
    RANKX ( ALL ( State ), [Total Customers (Payments)],, DESC, DENSE )
VAR __Result = __Current & " (Rank " & __Rank & ")"
RETURN
    __Result

'Visual Measure'[State Rank Title - State - Tooltip - Delivery] = 
VAR __Current =
    SELECTEDVALUE ( State[State] )
VAR __SelectedMetric = [Average Total Delivery Time (h)]
VAR __Rank =
    RANKX ( ALL ( State ), [Average Total Delivery Time (h)],, ASC, DENSE )
VAR __Result = __Current & " (Rank " & __Rank & ")"
RETURN
    __Result

'Visual Measure'[State Rank Title - State - Tooltip - Sales] = 
VAR __Current =
    SELECTEDVALUE ( State[State] )
VAR __SelectedMetric = [Selected Sales Metric]
VAR __Rank =
    RANKX ( ALL ( State ), [Selected Sales Metric],, DESC, DENSE )
VAR __Result = __Current & " (Rank " & __Rank & ")"
RETURN
    __Result

'Visual Measure'[Top 3 Categories - State - Tooltip - Sales] = 
VAR __SelectedMetric =
    SWITCH (
        TRUE (),
        MAX ( 'Sales Metric'[Sales Metric] ) = "Revenue", "Revenue",
        MAX ( 'Sales Metric'[Sales Metric] ) = "Orders", "Orders"
    )
VAR __TopCategories =
    TOPN (
        3,
        SUMMARIZE (
            ALL ( Category ),
            Category[Category Name],
            "Sales", [Selected Sales Metric]
        ),
        [Sales], DESC
    )
VAR __Format =
    SWITCH (
        TRUE (),
        __SelectedMetric = "Revenue", "R$ # ### ###",
        __SelectedMetric = "Orders", "# ### ###"
    )
VAR __FormattedList =
    CONCATENATEX (
        __TopCategories,
        "• " & Category[Category Name] & ": "
            & FORMAT ( [Sales], __Format ),
        UNICHAR ( 10 ),
        [Sales], DESC
    )
VAR __Result =
    SWITCH (
        TRUE (),
        __SelectedMetric = "Revenue",
            "Top 3 Categories by State Revenue:" & UNICHAR ( 10 ) & __FormattedList,
        __SelectedMetric = "Orders",
            "Top 3 Categories by State Orders:" & UNICHAR ( 10 ) & __FormattedList
    )
RETURN
    __Result

'Visual Measure'[Top Customer Segment - State - Tooltip] = 
VAR __TopSegment =
    TOPN (
        1,
        SUMMARIZE (
            'Customer Segment',
            'Customer Segment'[Segment],
            "CustomerCount", [Total Customers]
        ),
        [CustomerCount], DESC
    )
VAR __Result =
    MAXX ( __TopSegment, 'Customer Segment'[Segment] )
RETURN
    __Result

'Visual Measure'[Total Categories - Sparkline - Card - Product] = 
// Static line color - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)
VAR LineColour = "%23344C69"
VAR PointColour = "%23F9F9F9"
VAR Defs = "<defs>
    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>
        <stop stop-color='#4D6A8D' offset='0' />
        <stop stop-color='#4D6A8D' offset='0.3' />
        <stop stop-color='#F9F9F9' offset='1' />
    </linearGradient>
</defs>" // "Date" field used Total Categories along the X axis
VAR XMinDate =
    MIN ( 'Calendar'[Start of Month] )
VAR XMaxDate =
    MAX ( 'Calendar'[Start of Month] ) // Obtain overall min and overall max measure values when evaluated for each date
VAR YMinValue =
    MINX ( VALUES ( 'Calendar'[Start of Month] ), CALCULATE ( [Total Categories] ) )
VAR YMaxValue =
    MAXX ( VALUES ( 'Calendar'[Start of Month] ), CALCULATE ( [Total Categories] ) ) // Build table of X & Y coordinates and fit to 50 x 150 viewbox
VAR SparklineTable =
    ADDCOLUMNS (
        SUMMARIZE ( 'Calendar', 'Calendar'[Start of Month] ),
        "X",
            INT (
                150
                    * DIVIDE ( 'Calendar'[Start of Month] - XMinDate, XMaxDate - XMinDate )
            ),
        "Y",
            INT ( 50 * DIVIDE ( [Total Categories] - YMinValue, YMaxValue - YMinValue ) )
    ) // Concatenate X & Y coordinates to build the sparkline
VAR Lines =
    CONCATENATEX (
        SparklineTable,
        [X] & "," & 50 - [Y],
        " ",
        'Calendar'[Start of Month]
    ) // Last data points on the line
VAR LastSparkYValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [Y] )
VAR LastSparkXValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [X] ) // Add to SVG, and verify Data Category is set to Image URL for this measure
VAR SVGImageURL = "data:image/svg+xml;utf8," & --- gradient---
"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>" & Defs & "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' 
      stroke-width='0' points=' 0 50 " & Lines & " 150 150 Z '/>" & --- Lines---
"<polyline 
        fill='transparent' stroke='" & LineColour & "' 
        stroke-linecap='round' stroke-linejoin='round' 
        stroke-width='2' points=' " & Lines & " '/>" & --- Last Point---
"<circle cx='" & LastSparkXValue & "' cy='" & 50 - LastSparkYValue & "' r='4' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" & "</svg>"
RETURN
    SVGImageURL

'Visual Measure'[Total Categories - Subtitle - Card - Product] = 
VAR __Arrow =
    SWITCH (
        TRUE (),
        [LM MOM % Total Categories] > 0, UNICHAR ( 11165 ),
        [LM MOM % Total Categories] < 0, UNICHAR ( 11167 )
    )
VAR __Negative =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Total Categories], "0.00%" ) & " MOM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Positive =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Total Categories], "0.00%" ) & " MOM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Result =
    SWITCH (
        TRUE (),
        ISBLANK ( [LM MOM % Total Categories] ), "-",
        [LM MOM % Total Categories] = 0, "No MoM Change",
        [LM MOM % Total Categories] < 0, __Negative,
        [LM MOM % Total Categories] > 0, __Positive
    )
RETURN
    __Result

'Visual Measure'[Total Customers - Sparkline - Card - Customer] = 
// Static line color - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)
VAR LineColour = "%23344C69"
VAR PointColour = "%23F9F9F9"
VAR Defs = "<defs>
    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>
        <stop stop-color='#4D6A8D' offset='0' />
        <stop stop-color='#4D6A8D' offset='0.3' />
        <stop stop-color='#F9F9F9' offset='1' />
    </linearGradient>
</defs>" // "Date" field used in this example along the X axis
VAR XMinDate =
    MIN ( 'Calendar'[Start of Month] )
VAR XMaxDate =
    MAX ( 'Calendar'[Start of Month] ) // Obtain overall min and overall max measure values when evaluated for each date
VAR YMinValue =
    MINX (
        VALUES ( 'Calendar'[Start of Month] ),
        CALCULATE ( [Total Customers (Payments)] )
    )
VAR YMaxValue =
    MAXX (
        VALUES ( 'Calendar'[Start of Month] ),
        CALCULATE ( [Total Customers (Payments)] )
    ) // Build table of X & Y coordinates and fit to 50 x 150 viewbox
VAR SparklineTable =
    ADDCOLUMNS (
        SUMMARIZE ( 'Calendar', 'Calendar'[Start of Month] ),
        "X",
            INT (
                150
                    * DIVIDE ( 'Calendar'[Start of Month] - XMinDate, XMaxDate - XMinDate )
            ),
        "Y",
            INT (
                50
                    * DIVIDE ( [Total Customers (Payments)] - YMinValue, YMaxValue - YMinValue )
            )
    ) // Concatenate X & Y coordinates to build the sparkline
VAR Lines =
    CONCATENATEX (
        SparklineTable,
        [X] & "," & 50 - [Y],
        " ",
        'Calendar'[Start of Month]
    ) // Last data points on the line
VAR LastSparkYValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [Y] )
VAR LastSparkXValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [X] ) // Add to SVG, and verify Data Category is set to Image URL for this measure
VAR SVGImageURL = "data:image/svg+xml;utf8," & --- gradient---
"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>" & Defs & "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' 
      stroke-width='0' points=' 0 50 " & Lines & " 150 150 Z '/>" & --- Lines---
"<polyline 
        fill='transparent' stroke='" & LineColour & "' 
        stroke-linecap='round' stroke-linejoin='round' 
        stroke-width='2' points=' " & Lines & " '/>" & --- Last Point---
"<circle cx='" & LastSparkXValue & "' cy='" & 50 - LastSparkYValue & "' r='4' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" & "</svg>"
RETURN
    SVGImageURL

'Visual Measure'[Total Customers - Subtitle - Card - Customer] = 
VAR __Arrow =
    SWITCH (
        TRUE (),
        [LM MOM % Total Customers (Payments)] > 0, UNICHAR ( 11165 ),
        [LM MOM % Total Customers (Payments)] < 0, UNICHAR ( 11167 )
    )
VAR __Negative =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Total Customers (Payments)], "0.00%" ) & " MoM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Positive =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Total Customers (Payments)], "0.00%" ) & " MoM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Result =
    SWITCH (
        TRUE (),
        ISBLANK ( [LM MOM % Total Customers (Payments)] ), "-",
        [LM MOM % Total Customers (Payments)] = 0, "No MoM Change",
        [LM MOM % Total Customers (Payments)] < 0, __Negative,
        [LM MOM % Total Customers (Payments)] > 0, __Positive
    )
RETURN
    __Result

'Visual Measure'[Total Customers - Title Color - Card - Customer] = 
SWITCH (
    TRUE (),
    [LM MOM % Total Customers (Payments)] > 0, [Positive Color],
    [LM MOM % Total Customers (Payments)] < 0, [Negative Color]
)

'Visual Measure'[Total Customers State - Axis - Bar State - Customer] = 
VAR __MaxValue =
    MAXX ( ALLSELECTED ( State[State] ), [Total Customers (Payments)] )
VAR __Result = __MaxValue * 1.2
RETURN
    __Result

'Visual Measure'[Total Customers State - Bar Color - Bar State - Customer] = 
VAR __StateRank =
    IF (
        ISINSCOPE ( State[State] ),
        RANKX ( ALLSELECTED ( State[State] ), [Total Customers (Payments)] )
    )
VAR __Result =
    IF ( __StateRank <= 3, [Focus Blue], [Light Grey] )
RETURN
    __Result

'Visual Measure'[Total Customers State - Label Color - Bar State - Customer] = 
VAR __StateRank =
    IF (
        ISINSCOPE ( State[State] ),
        RANKX ( ALLSELECTED ( State[State] ), [Total Customers (Payments)] )
    )
VAR __Result =
    IF ( __StateRank <= 3, [Focus Blue], [Transparent Color] )
RETURN
    __Result

'Visual Measure'[Total Delivery Time Icon] = 
"data:image/svg+xml;utf8," & "<svg width='46' height='46' viewBox='0 0 46 46' fill='none' xmlns='http://www.w3.org/2000/svg'>
<path d='M44.0846 22.9998C44.0846 23.6793 44.0524 24.3513 43.9896 25.0143C42.9036 23.9277 41.6321 23.0267 40.2266 22.3625C39.8914 13.1381 32.3077 5.76293 23.0013 5.76293C13.4816 5.76293 5.76439 13.4802 5.76439 22.9998C5.76439 32.3062 13.1396 39.8899 22.364 40.2251C23.0281 41.6306 23.9292 42.9021 25.0157 43.9881C24.3527 44.051 23.6808 44.0832 23.0013 44.0832C11.3573 44.0832 1.91797 34.6438 1.91797 22.9998C1.91797 11.3558 11.3573 1.9165 23.0013 1.9165C34.6452 1.9165 44.0846 11.3558 44.0846 22.9998Z' fill='#344C69'/>
<path d='M24.9154 22.7725L26.5303 23.7049C25.461 24.4955 24.5132 25.4414 23.7205 26.509L22.0737 25.5581C21.7408 25.3659 21.4874 25.0889 21.3249 24.7702C21.082 24.3943 21.082 23.8947 21.082 23.8947V11.5002C21.082 10.4416 21.9401 9.5835 22.9987 9.5835C24.0573 9.5835 24.9154 10.4416 24.9154 11.5002V22.7725Z' fill='#344C69'/>
<path d='M29.3113 33.9386C30.0598 33.1901 31.2734 33.1901 32.0219 33.9386L33.2507 35.1673L36.8906 31.5274C37.6393 30.7789 38.8527 30.7789 39.6012 31.5274C40.3498 32.2761 40.3498 33.4895 39.6012 34.2381L34.7324 39.1069C34.5668 39.2725 34.3786 39.4015 34.1776 39.4936C33.4435 39.923 32.485 39.8229 31.8555 39.1933L29.3113 36.6491C28.5629 35.9007 28.5629 34.687 29.3113 33.9386Z' fill='#344C69'/>
<path fill-rule='evenodd' clip-rule='evenodd' d='M34.5 46C40.8513 46 46 40.8513 46 34.5C46 28.1487 40.8513 23 34.5 23C28.1487 23 23 28.1487 23 34.5C23 40.8513 28.1487 46 34.5 46ZM34.5 42.2014C30.2467 42.2014 26.7986 38.7533 26.7986 34.5C26.7986 30.2467 30.2467 26.7986 34.5 26.7986C38.7533 26.7986 42.2014 30.2467 42.2014 34.5C42.2014 38.7533 38.7533 42.2014 34.5 42.2014Z' fill='#344C69'/>
</svg>"

'Visual Measure'[Total Freight Value - Sparkline - Card - Product] = 
// Static line color - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)
VAR LineColour = "%23344C69"
VAR PointColour = "%23F9F9F9"
VAR Defs = "<defs>
    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>
        <stop stop-color='#4D6A8D' offset='0' />
        <stop stop-color='#4D6A8D' offset='0.3' />
        <stop stop-color='#F9F9F9' offset='1' />
    </linearGradient>
</defs>" // "Date" field used Total Categories along the X axis
VAR XMinDate =
    MIN ( 'Calendar'[Start of Month] )
VAR XMaxDate =
    MAX ( 'Calendar'[Start of Month] ) // Obtain overall min and overall max measure values when evaluated for each date
VAR YMinValue =
    MINX (
        VALUES ( 'Calendar'[Start of Month] ),
        CALCULATE ( [Total Freight Value] )
    )
VAR YMaxValue =
    MAXX (
        VALUES ( 'Calendar'[Start of Month] ),
        CALCULATE ( [Total Freight Value] )
    ) // Build table of X & Y coordinates and fit to 50 x 150 viewbox
VAR SparklineTable =
    ADDCOLUMNS (
        SUMMARIZE ( 'Calendar', 'Calendar'[Start of Month] ),
        "X",
            INT (
                150
                    * DIVIDE ( 'Calendar'[Start of Month] - XMinDate, XMaxDate - XMinDate )
            ),
        "Y",
            INT ( 50 * DIVIDE ( [Total Freight Value] - YMinValue, YMaxValue - YMinValue ) )
    ) // Concatenate X & Y coordinates to build the sparkline
VAR Lines =
    CONCATENATEX (
        SparklineTable,
        [X] & "," & 50 - [Y],
        " ",
        'Calendar'[Start of Month]
    ) // Last data points on the line
VAR LastSparkYValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [Y] )
VAR LastSparkXValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [X] ) // Add to SVG, and verify Data Category is set to Image URL for this measure
VAR SVGImageURL = "data:image/svg+xml;utf8," & --- gradient---
"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>" & Defs & "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' 
      stroke-width='0' points=' 0 50 " & Lines & " 150 150 Z '/>" & --- Lines---
"<polyline 
        fill='transparent' stroke='" & LineColour & "' 
        stroke-linecap='round' stroke-linejoin='round' 
        stroke-width='2' points=' " & Lines & " '/>" & --- Last Point---
"<circle cx='" & LastSparkXValue & "' cy='" & 50 - LastSparkYValue & "' r='4' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" & "</svg>"
RETURN
    SVGImageURL

'Visual Measure'[Total Freight Value - Subtitle - Card - Sales] = 
VAR __Arrow =
    SWITCH (
        TRUE (),
        [LM MOM % Total Freight Value] > 0, UNICHAR ( 11165 ),
        [LM MOM % Total Freight Value] < 0, UNICHAR ( 11167 )
    )
VAR __Negative =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Total Freight Value], "0.00%" ) & " MoM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Positive =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Total Freight Value], "0.00%" ) & " MoM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Result =
    SWITCH (
        TRUE (),
        ISBLANK ( [LM MOM % Total Freight Value] ), "-",
        [LM MOM % Total Freight Value] = 0, "No MoM Change",
        [LM MOM % Total Freight Value] < 0, __Negative,
        [LM MOM % Total Freight Value] > 0, __Positive
    )
RETURN
    __Result

'Visual Measure'[Total Ordered Products - Sparkline - Card - Product] = 
// Static line color - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)
VAR LineColour = "%23344C69"
VAR PointColour = "%23F9F9F9"
VAR Defs = "<defs>
    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>
        <stop stop-color='#4D6A8D' offset='0' />
        <stop stop-color='#4D6A8D' offset='0.3' />
        <stop stop-color='#F9F9F9' offset='1' />
    </linearGradient>
</defs>" // "Date" field used in this example along the X axis
VAR XMinDate =
    MIN ( 'Calendar'[Start of Month] )
VAR XMaxDate =
    MAX ( 'Calendar'[Start of Month] ) // Obtain overall min and overall max measure values when evaluated for each date
VAR YMinValue =
    MINX (
        VALUES ( 'Calendar'[Start of Month] ),
        CALCULATE ( [Total Ordered Products] )
    )
VAR YMaxValue =
    MAXX (
        VALUES ( 'Calendar'[Start of Month] ),
        CALCULATE ( [Total Ordered Products] )
    ) // Build table of X & Y coordinates and fit to 50 x 150 viewbox
VAR SparklineTable =
    ADDCOLUMNS (
        SUMMARIZE ( 'Calendar', 'Calendar'[Start of Month] ),
        "X",
            INT (
                150
                    * DIVIDE ( 'Calendar'[Start of Month] - XMinDate, XMaxDate - XMinDate )
            ),
        "Y",
            INT (
                50
                    * DIVIDE ( [Total Ordered Products] - YMinValue, YMaxValue - YMinValue )
            )
    ) // Concatenate X & Y coordinates to build the sparkline
VAR Lines =
    CONCATENATEX (
        SparklineTable,
        [X] & "," & 50 - [Y],
        " ",
        'Calendar'[Start of Month]
    ) // Last data points on the line
VAR LastSparkYValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [Y] )
VAR LastSparkXValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [X] ) // Add to SVG, and verify Data Category is set to Image URL for this measure
VAR SVGImageURL = "data:image/svg+xml;utf8," & --- gradient---
"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>" & Defs & "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' 
      stroke-width='0' points=' 0 50 " & Lines & " 150 150 Z '/>" & --- Lines---
"<polyline 
        fill='transparent' stroke='" & LineColour & "' 
        stroke-linecap='round' stroke-linejoin='round' 
        stroke-width='2' points=' " & Lines & " '/>" & --- Last Point---
"<circle cx='" & LastSparkXValue & "' cy='" & 50 - LastSparkYValue & "' r='4' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" & "</svg>"
RETURN
    SVGImageURL

'Visual Measure'[Total Ordered Products - Subtitle - Card - Product] = 
VAR __Arrow =
    SWITCH (
        TRUE (),
        [LM MOM % Total Ordered Products] > 0, UNICHAR ( 11165 ),
        [LM MOM % Total Ordered Products] < 0, UNICHAR ( 11167 )
    )
VAR __Negative =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Total Ordered Products], "0.00%" ) & " MOM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Positive =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Total Ordered Products], "0.00%" ) & " MOM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Result =
    SWITCH (
        TRUE (),
        ISBLANK ( [LM MOM % Total Ordered Products] ), "-",
        [LM MOM % Total Ordered Products] = 0, "No MoM Change",
        [LM MOM % Total Ordered Products] < 0, __Negative,
        [LM MOM % Total Ordered Products] > 0, __Positive
    )
RETURN
    __Result

'Visual Measure'[Total Ordered Products - Title Color - Card - Product] = 
SWITCH (
    TRUE (),
    [LM MOM % Total Ordered Products] > 0, [Positive Color],
    [LM MOM % Total Ordered Products] < 0, [Negative Color]
)

'Visual Measure'[Total Orders - Sparkline - Card - Sales] = 
// Static line color - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)
VAR LineColour = "%23344C69"
VAR PointColour = "%23F9F9F9"
VAR Defs = "<defs>
    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>
        <stop stop-color='#4D6A8D' offset='0' />
        <stop stop-color='#4D6A8D' offset='0.3' />
        <stop stop-color='#F9F9F9' offset='1' />
    </linearGradient>
</defs>" // "Date" field used in this example along the X axis
VAR XMinDate =
    MIN ( 'Calendar'[Start of Month] )
VAR XMaxDate =
    MAX ( 'Calendar'[Start of Month] ) // Obtain overall min and overall max measure values when evaluated for each date
VAR YMinValue =
    MINX ( VALUES ( 'Calendar'[Start of Month] ), CALCULATE ( [Total Orders] ) )
VAR YMaxValue =
    MAXX ( VALUES ( 'Calendar'[Start of Month] ), CALCULATE ( [Total Orders] ) ) // Build table of X & Y coordinates and fit to 50 x 150 viewbox
VAR SparklineTable =
    ADDCOLUMNS (
        SUMMARIZE ( 'Calendar', 'Calendar'[Start of Month] ),
        "X",
            INT (
                150
                    * DIVIDE ( 'Calendar'[Start of Month] - XMinDate, XMaxDate - XMinDate )
            ),
        "Y",
            INT ( 50 * DIVIDE ( [Total Orders] - YMinValue, YMaxValue - YMinValue ) )
    ) // Concatenate X & Y coordinates to build the sparkline
VAR Lines =
    CONCATENATEX (
        SparklineTable,
        [X] & "," & 50 - [Y],
        " ",
        'Calendar'[Start of Month]
    ) // Last data points on the line
VAR LastSparkYValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [Y] )
VAR LastSparkXValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [X] ) // Add to SVG, and verify Data Category is set to Image URL for this measure
VAR SVGImageURL = "data:image/svg+xml;utf8," & --- gradient---
"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>" & Defs & "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' 
      stroke-width='0' points=' 0 50 " & Lines & " 150 150 Z '/>" & --- Lines---
"<polyline 
        fill='transparent' stroke='" & LineColour & "' 
        stroke-linecap='round' stroke-linejoin='round' 
        stroke-width='2' points=' " & Lines & " '/>" & --- Last Point---
"<circle cx='" & LastSparkXValue & "' cy='" & 50 - LastSparkYValue & "' r='4' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" & "</svg>"
RETURN
    SVGImageURL

'Visual Measure'[Total Orders - Title - Subtitle - Sales] = 
VAR __Arrow =
    SWITCH (
        TRUE (),
        [LM MOM % Total Orders] > 0, UNICHAR ( 11165 ),
        [LM MOM % Total Orders] < 0, UNICHAR ( 11167 )
    )
VAR __Negative =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Total Orders], "0.00%" ) & " MoM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Positive =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Total Orders], "0.00%" ) & " MoM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Result =
    SWITCH (
        TRUE (),
        ISBLANK ( [LM MOM % Total Orders] ), "-",
        [LM MOM % Total Orders] < 0, __Negative,
        [LM MOM % Total Orders] > 0, __Positive
    )
RETURN
    __Result

'Visual Measure'[Total Orders - Title Color - Card - Sales] = 
SWITCH (
    TRUE (),
    [LM MOM % Total Orders] > 0, [Positive Color],
    [LM MOM % Total Orders] < 0, [Negative Color]
)

'Visual Measure'[Total Product Metric - Pareto Category - Product] = 
CALCULATE ( [Selected Product Metric], ALL ( 'Orders' ) )

'Visual Measure'[Total Products - Sparkline - Card - Product] = 
// Static line color - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)
VAR LineColour = "%23344C69"
VAR PointColour = "%23F9F9F9"
VAR Defs = "<defs>
    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>
        <stop stop-color='#4D6A8D' offset='0' />
        <stop stop-color='#4D6A8D' offset='0.3' />
        <stop stop-color='#F9F9F9' offset='1' />
    </linearGradient>
</defs>" // "Date" field used Total Categories along the X axis
VAR XMinDate =
    MIN ( 'Calendar'[Start of Month] )
VAR XMaxDate =
    MAX ( 'Calendar'[Start of Month] ) // Obtain overall min and overall max measure values when evaluated for each date
VAR YMinValue =
    MINX ( VALUES ( 'Calendar'[Start of Month] ), CALCULATE ( [Total Products] ) )
VAR YMaxValue =
    MAXX ( VALUES ( 'Calendar'[Start of Month] ), CALCULATE ( [Total Products] ) ) // Build table of X & Y coordinates and fit to 50 x 150 viewbox
VAR SparklineTable =
    ADDCOLUMNS (
        SUMMARIZE ( 'Calendar', 'Calendar'[Start of Month] ),
        "X",
            INT (
                150
                    * DIVIDE ( 'Calendar'[Start of Month] - XMinDate, XMaxDate - XMinDate )
            ),
        "Y",
            INT ( 50 * DIVIDE ( [Total Products] - YMinValue, YMaxValue - YMinValue ) )
    ) // Concatenate X & Y coordinates to build the sparkline
VAR Lines =
    CONCATENATEX (
        SparklineTable,
        [X] & "," & 50 - [Y],
        " ",
        'Calendar'[Start of Month]
    ) // Last data points on the line
VAR LastSparkYValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [Y] )
VAR LastSparkXValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [X] ) // Add to SVG, and verify Data Category is set to Image URL for this measure
VAR SVGImageURL = "data:image/svg+xml;utf8," & --- gradient---
"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>" & Defs & "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' 
      stroke-width='0' points=' 0 50 " & Lines & " 150 150 Z '/>" & --- Lines---
"<polyline 
        fill='transparent' stroke='" & LineColour & "' 
        stroke-linecap='round' stroke-linejoin='round' 
        stroke-width='2' points=' " & Lines & " '/>" & --- Last Point---
"<circle cx='" & LastSparkXValue & "' cy='" & 50 - LastSparkYValue & "' r='4' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" & "</svg>"
RETURN
    SVGImageURL

'Visual Measure'[Total Products - Subtitle - Card - Product] = 
VAR __Arrow =
    SWITCH (
        TRUE (),
        [LM MOM % Total Products] > 0, UNICHAR ( 11165 ),
        [LM MOM % Total Products] < 0, UNICHAR ( 11167 )
    )
VAR __Negative =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Total Products], "0.00%" ) & " MOM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Positive =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Total Products], "0.00%" ) & " MOM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Result =
    SWITCH (
        TRUE (),
        ISBLANK ( [LM MOM % Total Products] ), "-",
        [LM MOM % Total Products] = 0, "No MoM Change",
        [LM MOM % Total Products] < 0, __Negative,
        [LM MOM % Total Products] > 0, __Positive
    )
RETURN
    __Result

'Visual Measure'[Total Products - Title Color - Card - Product] = 
SWITCH (
    TRUE (),
    [LM MOM % Total Products] > 0, [Positive Color],
    [LM MOM % Total Products] < 0, [Negative Color]
)

'Visual Measure'[Total Revenue - Sparkline - Card - Sales] = 
// Static line color - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)
VAR LineColour = "%23344C69"
VAR PointColour = "%23F9F9F9"
VAR Defs = "<defs>
    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>
        <stop stop-color='#4D6A8D' offset='0' />
        <stop stop-color='#4D6A8D' offset='0.3' />
        <stop stop-color='#F9F9F9' offset='1' />
    </linearGradient>
</defs>" // "Date" field used in this example along the X axis
VAR XMinDate =
    MIN ( 'Calendar'[Start of Month] )
VAR XMaxDate =
    MAX ( 'Calendar'[Start of Month] ) // Obtain overall min and overall max measure values when evaluated for each date
VAR YMinValue =
    MINX (
        VALUES ( 'Calendar'[Start of Month] ),
        CALCULATE ( [Total Revenue (Payments)] )
    )
VAR YMaxValue =
    MAXX (
        VALUES ( 'Calendar'[Start of Month] ),
        CALCULATE ( [Total Revenue (Payments)] )
    ) // Build table of X & Y coordinates and fit to 50 x 150 viewbox
VAR SparklineTable =
    ADDCOLUMNS (
        SUMMARIZE ( 'Calendar', 'Calendar'[Start of Month] ),
        "X",
            INT (
                150
                    * DIVIDE ( 'Calendar'[Start of Month] - XMinDate, XMaxDate - XMinDate )
            ),
        "Y",
            INT (
                50
                    * DIVIDE ( [Total Revenue (Payments)] - YMinValue, YMaxValue - YMinValue )
            )
    ) // Concatenate X & Y coordinates to build the sparkline
VAR Lines =
    CONCATENATEX (
        SparklineTable,
        [X] & "," & 50 - [Y],
        " ",
        'Calendar'[Start of Month]
    ) // Last data points on the line
VAR LastSparkYValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [Y] )
VAR LastSparkXValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [X] ) // Add to SVG, and verify Data Category is set to Image URL for this measure
VAR SVGImageURL = "data:image/svg+xml;utf8," & --- gradient---
"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>" & Defs & "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' 
      stroke-width='0' points=' 0 50 " & Lines & " 150 150 Z '/>" & --- Lines---
"<polyline 
        fill='transparent' stroke='" & LineColour & "' 
        stroke-linecap='round' stroke-linejoin='round' 
        stroke-width='2' points=' " & Lines & " '/>" & --- Last Point---
"<circle cx='" & LastSparkXValue & "' cy='" & 50 - LastSparkYValue & "' r='4' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" & "</svg>"
RETURN
    SVGImageURL

'Visual Measure'[Total Revenue (Payments) - Subtitle - Card - Sales] = 
VAR __Arrow =
    SWITCH (
        TRUE (),
        [LM MOM % Total Revenue (Payments)] > 0, UNICHAR ( 11165 ),
        [LM MOM % Total Revenue (Payments)] < 0, UNICHAR ( 11167 )
    )
VAR __Negative =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Total Revenue (Payments)], "0.00%" ) & " MoM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Positive =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Total Revenue (Payments)], "0.00%" ) & " MoM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Result =
    SWITCH (
        TRUE (),
        ISBLANK ( [LM MOM % Total Revenue (Payments)] ), "-",
        [LM MOM % Total Revenue (Payments)] < 0, __Negative,
        [LM MOM % Total Revenue (Payments)] > 0, __Positive
    )
RETURN
    __Result

'Visual Measure'[Total Revenue (Payments) - Title Color - Card - Sales] = 
SWITCH (
    TRUE (),
    [LM MOM % Total Revenue (Payments)] > 0, [Positive Color],
    [LM MOM % Total Revenue (Payments)] < 0, [Negative Color]
)

'Visual Measure'[Total Sales Metric - Pareto Seller - Sales] = 
CALCULATE ( [Selected Sales Metric], ALL ( 'Orders' ) )

'Visual Measure'[Total Sellers - Sparkline - Card - Sales] = 
// Static line color - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)
VAR LineColour = "%23344C69"
VAR PointColour = "%23F9F9F9"
VAR Defs = "<defs>
    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>
        <stop stop-color='#4D6A8D' offset='0' />
        <stop stop-color='#4D6A8D' offset='0.3' />
        <stop stop-color='#F9F9F9' offset='1' />
    </linearGradient>
</defs>" // "Date" field used in this example along the X axis
VAR XMinDate =
    MIN ( 'Calendar'[Start of Month] )
VAR XMaxDate =
    MAX ( 'Calendar'[Start of Month] ) // Obtain overall min and overall max measure values when evaluated for each date
VAR YMinValue =
    MINX ( VALUES ( 'Calendar'[Start of Month] ), CALCULATE ( [Total Sellers] ) )
VAR YMaxValue =
    MAXX ( VALUES ( 'Calendar'[Start of Month] ), CALCULATE ( [Total Sellers] ) ) // Build table of X & Y coordinates and fit to 50 x 150 viewbox
VAR SparklineTable =
    ADDCOLUMNS (
        SUMMARIZE ( 'Calendar', 'Calendar'[Start of Month] ),
        "X",
            INT (
                150
                    * DIVIDE ( 'Calendar'[Start of Month] - XMinDate, XMaxDate - XMinDate )
            ),
        "Y",
            INT ( 50 * DIVIDE ( [Total Sellers] - YMinValue, YMaxValue - YMinValue ) )
    ) // Concatenate X & Y coordinates to build the sparkline
VAR Lines =
    CONCATENATEX (
        SparklineTable,
        [X] & "," & 50 - [Y],
        " ",
        'Calendar'[Start of Month]
    ) // Last data points on the line
VAR LastSparkYValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [Y] )
VAR LastSparkXValue =
    MAXX ( FILTER ( SparklineTable, 'Calendar'[Start of Month] = XMaxDate ), [X] ) // Add to SVG, and verify Data Category is set to Image URL for this measure
VAR SVGImageURL = "data:image/svg+xml;utf8," & --- gradient---
"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>" & Defs & "<polyline fill='url(#grad)' fill-opacity='0.3' stroke='transparent' 
      stroke-width='0' points=' 0 50 " & Lines & " 150 150 Z '/>" & --- Lines---
"<polyline 
        fill='transparent' stroke='" & LineColour & "' 
        stroke-linecap='round' stroke-linejoin='round' 
        stroke-width='2' points=' " & Lines & " '/>" & --- Last Point---
"<circle cx='" & LastSparkXValue & "' cy='" & 50 - LastSparkYValue & "' r='4' stroke='" & LineColour & "' stroke-width='2' fill='" & PointColour & "' />" & "</svg>"
RETURN
    SVGImageURL

'Visual Measure'[Total Sellers - Subtitle - Card - Sales] = 
VAR __Arrow =
    SWITCH (
        TRUE (),
        [LM MOM % Total Sellers] > 0, UNICHAR ( 11165 ),
        [LM MOM % Total Sellers] < 0, UNICHAR ( 11167 )
    )
VAR __Negative =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Total Sellers], "0.00%" ) & " MOM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Positive =
    __Arrow & REPT ( " ", 2 )
        & FORMAT ( [LM MOM % Total Sellers], "0.00%" ) & " MOM Change"
        & REPT ( " ", 2 ) & __Arrow
VAR __Result =
    SWITCH (
        TRUE (),
        ISBLANK ( [LM MOM % Total Sellers] ), "-",
        [LM MOM % Total Sellers] = 0, "No MoM Change",
        [LM MOM % Total Sellers] < 0, __Negative,
        [LM MOM % Total Sellers] > 0, __Positive
    )
RETURN
    __Result

'Visual Measure'[Total Sellers - Title Color - Card - Sales] = 
SWITCH (
    TRUE (),
    [LM MOM % Total Sellers] > 0, [Positive Color],
    [LM MOM % Total Sellers] < 0, [Negative Color]
)

'Visual Measure'[Transparent Color] = 
"RGBA(0, 0, 0, 0)"